import { appSchema, tableSchema } from "@nozbe/watermelondb";

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: "dtr_entries",
      columns: [
        { name: "tenant_id", type: "string" },
        { name: "user_id", type: "string" },
        { name: "clock_in_at", type: "number" },
        { name: "clock_out_at", type: "number", isOptional: true },
        { name: "clock_in_lat", type: "number" },
        { name: "clock_in_lng", type: "number" },
        { name: "clock_out_lat", type: "number", isOptional: true },
        { name: "clock_out_lng", type: "number", isOptional: true },
        { name: "clock_in_accuracy", type: "number", isOptional: true },
        { name: "clock_out_accuracy", type: "number", isOptional: true },
        { name: "status", type: "string" },
        { name: "synced", type: "boolean" },
        { name: "server_id", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "tasks",
      columns: [
        { name: "tenant_id", type: "string" },
        { name: "server_id", type: "string" },
        { name: "title", type: "string" },
        { name: "description", type: "string", isOptional: true },
        { name: "status", type: "string" },
        { name: "priority", type: "string" },
        { name: "assigned_to", type: "string", isOptional: true },
        { name: "due_date", type: "number", isOptional: true },
        { name: "project_id", type: "string", isOptional: true },
        { name: "synced", type: "boolean" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "expenses",
      columns: [
        { name: "tenant_id", type: "string" },
        { name: "user_id", type: "string" },
        { name: "amount", type: "number" },
        { name: "currency", type: "string" },
        { name: "category", type: "string" },
        { name: "description", type: "string", isOptional: true },
        { name: "receipt_uri", type: "string", isOptional: true },
        { name: "status", type: "string" },
        { name: "synced", type: "boolean" },
        { name: "server_id", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "payslips",
      columns: [
        { name: "tenant_id", type: "string" },
        { name: "user_id", type: "string" },
        { name: "server_id", type: "string" },
        { name: "period_start", type: "number" },
        { name: "period_end", type: "number" },
        { name: "gross_pay", type: "number" },
        { name: "net_pay", type: "number" },
        { name: "deductions", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "sync_queue",
      columns: [
        { name: "entity_type", type: "string" },
        { name: "entity_id", type: "string" },
        { name: "action", type: "string" },
        { name: "payload", type: "string" },
        { name: "attempts", type: "number" },
        { name: "last_error", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
      ],
    }),
  ],
});
