#!/usr/bin/env node
/**
 * design-build.mjs — V32.8 Rule 31 token compiler
 *
 * Reads tokens/src/orqafy.tokens.json and emits:
 *   tokens/build/generated-tokens.css   — CSS custom properties (--sd-* prefixed)
 *   tokens/build/tokens.d.ts            — TypeScript token-name union + const map
 *
 * Invoked via: npm run design:build
 * Always run design:validate first; this script does not re-validate.
 *
 * No external dependencies — pure Node.js. This avoids requiring style-dictionary
 * as a production devDependency. If style-dictionary is added later, replace this
 * script with `style-dictionary build --config sd.config.mjs`.
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT      = resolve(__dirname, "..");
const TOKEN_SRC = resolve(ROOT, "tokens/src/orqafy.tokens.json");
const BUILD_DIR = resolve(ROOT, "tokens/build");

mkdirSync(BUILD_DIR, { recursive: true });

const tokens = JSON.parse(readFileSync(TOKEN_SRC, "utf8"));

// ── Flatten tokens to { "category-key": { $value, $description } } ────────

function flatten(obj, prefix = "") {
  const result = {};
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith("$")) continue;                     // skip $type, $metadata, etc.
    const key = prefix ? `${prefix}-${k}` : k;
    if (typeof v === "object" && v !== null && !("$value" in v)) {
      Object.assign(result, flatten(v, key));
    } else if (typeof v === "object" && v !== null && "$value" in v) {
      result[key] = { $value: v.$value, $description: v.$description ?? "" };
    }
  }
  return result;
}

const flat = flatten(tokens);

// ── Generate CSS ───────────────────────────────────────────────────────────

const cssLines = [
  `/**`,
  ` * generated-tokens.css — Orqafy Design Tokens (V32.8 Rule 31)`,
  ` * AUTO-GENERATED by scripts/design-build.mjs — do not edit manually.`,
  ` * Source: tokens/src/orqafy.tokens.json`,
  ` * Generated: ${new Date().toISOString()}`,
  ` *`,
  ` * These are reference-only CSS variables (--sd-* prefix).`,
  ` * The active runtime variables (--background, --primary, etc.) are in`,
  ` * apps/web/src/app/globals.css and are the source of truth for the UI.`,
  ` */`,
  ``,
  `:root {`,
];

for (const [key, token] of Object.entries(flat)) {
  const cssVar = `--sd-${key}`;
  const val    = Array.isArray(token.$value)
    ? token.$value.join(", ")
    : String(token.$value);
  const desc = token.$description ? `  /* ${token.$description} */` : "";
  cssLines.push(`  ${cssVar}: ${val};${desc}`);
}

cssLines.push(`}`);

const cssOut = cssLines.join("\n") + "\n";
writeFileSync(resolve(BUILD_DIR, "generated-tokens.css"), cssOut, "utf8");
console.log(`[design:build] Wrote tokens/build/generated-tokens.css (${Object.keys(flat).length} tokens)`);

// ── Generate TypeScript declarations ──────────────────────────────────────

const tokenNames = Object.keys(flat).map((k) => `  | ${JSON.stringify(k)}`).join("\n");
const tokenMap   = Object.entries(flat).map(([k, v]) => {
  const val = Array.isArray(v.$value) ? v.$value.join(", ") : String(v.$value);
  return `  ${JSON.stringify(k)}: ${JSON.stringify(val)},`;
}).join("\n");

const tsOut = `/**
 * tokens.d.ts — Orqafy Design Token Type Declarations (V32.8 Rule 31)
 * AUTO-GENERATED by scripts/design-build.mjs — do not edit manually.
 * Source: tokens/src/orqafy.tokens.json
 * Generated: ${new Date().toISOString()}
 */

/** Union of all valid design token names. */
export type TokenName =
${tokenNames};

/** Map of token name → resolved CSS value string. */
export declare const tokens: Record<TokenName, string>;
export declare const tokenMap: {
${tokenMap}
};
`;

writeFileSync(resolve(BUILD_DIR, "tokens.d.ts"), tsOut, "utf8");
console.log(`[design:build] Wrote tokens/build/tokens.d.ts`);
console.log(`[design:build] Done. Run "npm run design:check" to validate against baseline.`);
