// review-scope.mjs — deterministic code-review pre-scope tool (V32.51).
// Zero runtime deps (node:* stdlib only). Task 1: diff parser + conservative
// review-worthiness gate. Later tasks add the CLI entry behind the
// import.meta.url === main guard.
//
// DESIGN LAW 2 (conservative gate): default = INCLUDE. Only exclude
// certain-noise (lockfiles, generated output, binary/asset files, .snap
// snapshots, generated-header markers). Always KEEP .d.ts, deletions,
// tests, config, docs, migrations.

/**
 * Parse a unified diff (as produced by `git diff`) into per-file records.
 * @param {string} text
 * @returns {{path: string, status: string, added: string[]}[]}
 */
function parseDiff(text) {
  const lines = text.split("\n");
  const files = [];
  let current = null;

  const fileHeaderRe = /^diff --git a\/(.+?) b\/(.+)$/;

  for (const line of lines) {
    const headerMatch = line.match(fileHeaderRe);
    if (headerMatch) {
      current = { path: headerMatch[2], status: "modified", added: [] };
      files.push(current);
      continue;
    }
    if (!current) continue;

    if (line.startsWith("deleted file mode")) {
      current.status = "deleted";
      continue;
    }
    if (line.startsWith("rename from") || line.startsWith("rename to")) {
      current.status = "renamed";
      continue;
    }
    if (line.startsWith("new file mode")) {
      current.status = "added";
      continue;
    }
    if (line.startsWith("+++")) {
      // header line — never a content line, always skip
      continue;
    }
    if (line.startsWith("+")) {
      current.added.push(line.slice(1));
    }
  }

  return files;
}

const SKIP_PATTERNS = [
  /(^|\/)(pnpm-lock\.yaml|package-lock\.json|yarn\.lock)$/,
  /(^|\/)(dist|\.next|node_modules)\//,
  /\.(png|jpe?g|gif|svg|ico|webp|woff2?|map)$/i,
  /\.snap$/,
];

const GENERATED_HEADER_RE = /@generated|DO NOT EDIT|prisma-client|Code generated by/;

/**
 * Conservative review-worthiness gate. Default = INCLUDE; excludes only
 * certain-noise. Never excludes .d.ts, deletions, tests, config, docs,
 * migrations.
 * @param {string} path
 * @param {string[]} addedLines
 * @returns {{worthy: boolean, reason: string}}
 */
function reviewWorthy(path, addedLines) {
  for (const re of SKIP_PATTERNS) {
    if (re.test(path)) {
      return { worthy: false, reason: `matches skip pattern: ${re}` };
    }
  }

  const headSlice = (addedLines || []).slice(0, 5);
  if (headSlice.some((line) => GENERATED_HEADER_RE.test(line))) {
    return { worthy: false, reason: "generated-file header marker detected" };
  }

  return { worthy: true, reason: "no exclusion matched — default include" };
}

// ---------------------------------------------------------------------------
// L1-L6 security-lens resolution (Task 2). Lens IDs/why-strings mirror the
// canonical table in security.md §L1-L6 (guarded by a parity test — do not
// rename/reorder without also updating that table).
// ---------------------------------------------------------------------------

const LENS_RULES = [
  {
    id: "L1",
    why: "tenant-scoping",
    path: /(server\/|\/api\/|routers?\/|trpc)/,
    content: /(db|prisma|ctx\.db).*(findMany|findFirst|findUnique|count)/,
    rule: "signal",
  },
  {
    id: "L2",
    why: "input-validation",
    path: /(route\.(t|j)sx?$|actions?\.)/,
    content: /(req\.(json|formData|text)\(\)|NextRequest)/,
    rule: "signal",
  },
  {
    id: "L3",
    why: "rbac",
    path: /(middleware\.(t|j)s$|routers?\/|guard)/,
    content: /(publicProcedure|protectedProcedure|router\(|hasPermission|\brole\b)/,
    rule: "signal",
  },
  {
    id: "L4",
    why: "rate-limit+transport",
    path: /(route\.|auth|login|webhook)/,
    content: /(NextResponse|export async function (POST|PUT|DELETE|PATCH))/,
    rule: "signal",
  },
  {
    id: "L5",
    why: "audit-log",
    path: /(routers?\/|server\/)/,
    content: /(\.(create|update|delete|deleteMany|updateMany)\(|\.mutation\()/,
    rule: "signal",
  },
  {
    id: "L6",
    why: "prisma-guardrails",
    path: /schema\.prisma$/,
    content: /(deleteMany|updateMany|\{ id: \{ in:)/,
    rule: "signal",
  },
];

const ROUTE_HANDLER_RE = /(^|\/)app\/.*\/route\.(t|j)sx?$/;
const PAGES_API_RE = /(^|\/)pages\/api\//;
const ROUTE_HANDLER_FORCE_IDS = ["L1", "L3", "L4"];

const SCANNER_RULES = [
  {
    tool: "gitleaks",
    tier: 1,
    path: /\.env(\..+)?$/,
    content: /(api[_-]?key|secret|token|password)\s*[:=]\s*['"][A-Za-z0-9\-_]{16,}['"]/i,
  },
  { tool: "semgrep", tier: 1, path: /\.(ts|tsx|js|jsx)$/ },
  { tool: "tsc", tier: 1, path: /\.(ts|tsx)$/ },
  { tool: "eslint", tier: 1, path: /\.(ts|tsx|js|jsx)$/ },
  { tool: "trivy", tier: 2, path: /(^|\/)(Dockerfile|docker-compose\.ya?ml)$/i },
  { tool: "osv", tier: 2, path: /(^|\/)package\.json$/ },
  { tool: "syft", tier: 2, path: /(^|\/)package\.json$/ },
  {
    tool: "backstop",
    tier: 2,
    path: /page\.tsx$/,
    content: /return\s*\(\s*</,
  },
];

/**
 * Resolve L1-L6 security lenses for a review-worthy file. Fires on
 * pathHit||contentHit; confidence = "content" when the strong content
 * signal fired, else "path". Route handlers (app/**\/route.ts,
 * pages/api/**) unconditionally force-fire L1/L3/L4 at path confidence
 * (security.md: "Route Handlers bypass tRPC" — L1 tenant scoping, L3 RBAC,
 * and rate limiting are all inactive there).
 * @param {{path: string, added: string[]}} file
 * @returns {{id: string, why: string, confidence: string, rule: string}[]}
 */
function resolveLenses(file) {
  const content = (file.added || []).join("\n");
  const results = [];

  for (const lens of LENS_RULES) {
    const pathHit = lens.path ? lens.path.test(file.path) : false;
    const contentHit = lens.content ? lens.content.test(content) : false;
    if (pathHit || contentHit) {
      results.push({
        id: lens.id,
        why: lens.why,
        confidence: contentHit ? "content" : "path",
        rule: lens.rule || "signal",
      });
    }
  }

  const isRouteHandler = ROUTE_HANDLER_RE.test(file.path) || PAGES_API_RE.test(file.path);
  if (isRouteHandler) {
    for (const id of ROUTE_HANDLER_FORCE_IDS) {
      const existing = results.find((r) => r.id === id);
      if (!existing) {
        const lens = LENS_RULES.find((l) => l.id === id);
        results.push({
          id,
          why: lens.why,
          confidence: "path",
          rule: "route-handler-bypass",
        });
      } else if (existing.confidence === "path") {
        existing.rule = "route-handler-bypass";
      }
    }
  }

  return results;
}

/**
 * Resolve real audit-app.sh scanner tools for a review-worthy file. Same
 * fire logic as resolveLenses (pathHit||contentHit, confidence tag), no
 * route-handler override (scanners are tool-shaped, not security-lens).
 * @param {{path: string, added: string[]}} file
 * @returns {{tool: string, tier: number, confidence: string}[]}
 */
function resolveScanners(file) {
  const content = (file.added || []).join("\n");
  const results = [];

  for (const scanner of SCANNER_RULES) {
    const pathHit = scanner.path ? scanner.path.test(file.path) : false;
    const contentHit = scanner.content ? scanner.content.test(content) : false;
    if (pathHit || contentHit) {
      results.push({
        tool: scanner.tool,
        tier: scanner.tier,
        confidence: contentHit ? "content" : "path",
      });
    }
  }

  return results;
}

// ---------------------------------------------------------------------------
// Manifest emission (Task 3). FLOOR-not-ceiling posture: the manifest is a
// MINIMUM guaranteed set of lenses/scanners — it never caps or replaces the
// reviewer's own open-ended judgment. buildManifest is a pure function (no
// timestamp inside) so the returned object is deterministic; the CLI injects
// a `generated` ISO timestamp only at file-write time.
// ---------------------------------------------------------------------------

const FLOOR_NOTICE =
  "MINIMUM guaranteed lenses. This ADDS to the reviewer's own open-ended review; it never caps or replaces agent judgment. Absence of a lens here is NOT permission to skip it.";

/**
 * Build the deterministic pre-scope manifest from raw diff text.
 * @param {string} diffText
 * @param {{diffBase?: string}} [opts]
 * @returns {object}
 */
function buildManifest(diffText, opts = {}) {
  const diffBase = opts.diffBase || "working-tree";
  const parsed = parseDiff(diffText);

  const worthyFiles = [];
  const skipped = [];

  for (const file of parsed) {
    // Deletion handling FIRST — never run a deleted file through
    // resolveLenses (there is no surviving content to scan). Renames are
    // already parsed under their new b/ path by parseDiff, so they fall
    // through to the normal gate below.
    if (file.status === "deleted") {
      worthyFiles.push({
        file: file.path,
        reviewWorthy: true,
        reason: "deletion — verify no dangling refs/authz removal",
        lenses: [],
        scanners: [],
      });
      continue;
    }

    const gate = reviewWorthy(file.path, file.added);
    if (!gate.worthy) {
      skipped.push({ file: file.path, reason: gate.reason });
      continue;
    }

    worthyFiles.push({
      file: file.path,
      reviewWorthy: true,
      reason: gate.reason,
      lenses: resolveLenses(file),
      scanners: resolveScanners(file),
    });
  }

  return {
    schemaVersion: "1.0",
    generator: "review-scope.mjs",
    frameworkVersion: "V32.51",
    diffBase,
    posture: "FLOOR-NOT-CEILING",
    notice: FLOOR_NOTICE,
    lensAuthority: ".ai_prompt/security.md §L1-L6",
    scannerAuthority: "scripts/audit-app.sh (T1/T2)",
    summary: {
      filesChanged: parsed.length,
      reviewWorthy: worthyFiles.length,
      skipped: skipped.length,
    },
    files: worthyFiles,
    skipped,
  };
}

/**
 * Render the manifest as a human-readable markdown table, led by the
 * FLOOR-not-ceiling banner.
 * @param {object} manifest
 * @returns {string}
 */
function renderTable(manifest) {
  const lines = [];
  lines.push("# Review Pre-Scope Manifest (FLOOR, NOT CEILING)");
  lines.push("");
  lines.push(`> ${manifest.notice}`);
  lines.push(">");
  lines.push(
    `> Lens authority: \`${manifest.lensAuthority}\` · Scanner authority: \`${manifest.scannerAuthority}\``,
  );
  lines.push("");
  lines.push(
    `Diff base: \`${manifest.diffBase}\` · Files changed: ${manifest.summary.filesChanged} · Review-worthy: ${manifest.summary.reviewWorthy} · Skipped: ${manifest.summary.skipped}`,
  );
  lines.push("");

  lines.push("## Review-worthy files (minimum guaranteed lenses)");
  lines.push("");
  if (manifest.files.length === 0) {
    lines.push("_None._");
  } else {
    lines.push("| File | Lenses (id: why) | Scanners | Reason |");
    lines.push("|---|---|---|---|");
    for (const f of manifest.files) {
      const lensStr =
        f.lenses.length === 0
          ? "—"
          : f.lenses.map((l) => `${l.id}:${l.why}`).join(", ");
      const scannerStr =
        f.scanners.length === 0
          ? "—"
          : f.scanners.map((s) => s.tool).join(", ");
      lines.push(`| ${f.file} | ${lensStr} | ${scannerStr} | ${f.reason} |`);
    }
  }
  lines.push("");

  lines.push("## Skipped (certain-noise only)");
  lines.push("");
  if (manifest.skipped.length === 0) {
    lines.push("_None._");
  } else {
    lines.push("| File | Reason |");
    lines.push("|---|---|");
    for (const s of manifest.skipped) {
      lines.push(`| ${s.file} | ${s.reason} |`);
    }
  }
  lines.push("");

  return lines.join("\n");
}

export {
  parseDiff,
  reviewWorthy,
  LENS_RULES,
  SCANNER_RULES,
  resolveLenses,
  resolveScanners,
  buildManifest,
  renderTable,
};

// ---------------------------------------------------------------------------
// CLI entry (Task 3). Always exits 0 — this tool never blocks a review; on
// any failure to read a diff it falls back to an empty-diff manifest that
// explains what happened, still writes it, and exits 0.
// ---------------------------------------------------------------------------

if (import.meta.url === `file://${process.argv[1]}`) {
  const { readFileSync, mkdirSync, writeFileSync } = await import("node:fs");
  const { execSync } = await import("node:child_process");

  let diffText;
  let manifest;

  try {
    const args = process.argv.slice(2);
    const diffIdx = args.indexOf("--diff");
    const baseIdx = args.indexOf("--base");

    if (diffIdx !== -1 && args[diffIdx + 1]) {
      diffText = readFileSync(args[diffIdx + 1], "utf8");
    } else if (baseIdx !== -1 && args[baseIdx + 1]) {
      diffText = execSync(`git diff ${args[baseIdx + 1]}`, {
        encoding: "utf8",
        maxBuffer: 1024 * 1024 * 64,
      });
    } else {
      diffText = execSync("git diff", {
        encoding: "utf8",
        maxBuffer: 1024 * 1024 * 64,
      });
    }

    manifest = buildManifest(diffText, {});
  } catch (err) {
    manifest = buildManifest("", {});
    manifest.notice = `Diff could not be read (${err.message}). ${FLOOR_NOTICE}`;
  }

  const generated = new Date().toISOString();
  const manifestOut = { generated, ...manifest };

  try {
    mkdirSync("test-artifacts/review", { recursive: true });
    writeFileSync(
      "test-artifacts/review/review-manifest.json",
      JSON.stringify(manifestOut, null, 2) + "\n",
      "utf8",
    );
    writeFileSync(
      "test-artifacts/review/review-manifest.md",
      renderTable(manifest),
      "utf8",
    );
  } catch (err) {
    console.error("review-scope: could not write manifest:", err.message);
  }

  console.log(renderTable(manifest));
  process.exit(0);
}
