#!/bin/bash
# ═══════════════════════════════════════════════════════════════════
# Sync CREDENTIALS.md values → .env.dev / .env.staging / .env.prod
# ═══════════════════════════════════════════════════════════════════
# Generated by Phase 3 (V31). Run after filling ⏳ placeholders in CREDENTIALS.md.
# Safe to re-run — idempotent. Only writes values that are not still ⏳.
# Never echoes credential values to stdout. Never sends them to any AI context.
#
# Usage:
#   bash scripts/sync-credentials-to-env.sh
#
# What it propagates:
#   AI-generated (always present after Bootstrap Step 18):
#     - PostgreSQL DB_USER + DB_PASSWORD (per env)
#     - PgBouncer PGBOUNCER_AUTH_PASSWORD (per env)
#     - Valkey REDIS_PASSWORD (per env)
#     - MinIO STORAGE_ACCESS_KEY + STORAGE_SECRET_KEY (per env)
#     - pgAdmin PGADMIN_EMAIL + PGADMIN_PASSWORD (per env)
#     - Auth.js v5 AUTH_SECRET (per env)
#   Human-fill (⏳ until human edits CREDENTIALS.md):
#     - SMTP host/port/user/pass/from (staging + prod)
#     - Xendit SECRET_KEY/PUBLIC_KEY/WEBHOOK_TOKEN (per env)
#     - Cloudflare Turnstile LIVE keys (prod only)
#     - Komodo UI URL (staging + prod)
#     - Third-party API keys (project-specific rows)
# ═══════════════════════════════════════════════════════════════════

set -euo pipefail
CREDS="CREDENTIALS.md"

if [ ! -f "$CREDS" ]; then
  echo "❌ CREDENTIALS.md not found. Run Bootstrap Step 18 first."
  exit 1
fi

# Count remaining placeholders
pending=$(grep -c "⏳" "$CREDS" 2>/dev/null || echo 0)
echo "CREDENTIALS.md has $pending unfilled placeholders."
if [ "$pending" -gt 0 ]; then
  echo ""
  echo "Sections still containing ⏳ placeholders (review before Phase 5):"
  grep -B1 "⏳" "$CREDS" | grep "^##" | sort -u | head -20 || true
  echo ""
  echo "Phase 5 pre-flight will block on REQUIRED ⏳ fields. Filling continues..."
fi

# ─── Helpers ────────────────────────────────────────────────────────

# Extract a column value from a markdown table row in CREDENTIALS.md
# table_row_field <section_anchor> <env_name> <column_index_1based>
# section_anchor: a regex pattern matching the section header
# env_name: the value in the first column (dev|staging|prod)
# column_index: 1-based index of the column to extract
table_row_field() {
  local anchor="$1"
  local env="$2"
  local col="$3"
  awk -v a="$anchor" -v e="$env" -v c="$col" '
    $0 ~ a { in_section=1; next }
    in_section && /^## / { in_section=0 }
    in_section && /^\| *'"$2"' *\|/ {
      # split by pipe, trim each field
      n=split($0, f, "|")
      # field index in awk: f[1] is empty (before first pipe), f[2] is env name, f[3] is col 1
      val=f[c+2]
      gsub(/^ +| +$/, "", val)
      print val
      exit
    }
  ' "$CREDS"
}

# Update a key=value line in an env file. Skips ⏳ values and empty values.
# Adds the line if missing.
update_env() {
  local env_file="$1"
  local key="$2"
  local value="$3"

  [ ! -f "$env_file" ] && return 0
  [[ "$value" == *"⏳"* ]] && return 0
  [ -z "$value" ] && return 0
  [[ "$value" == "[dev port]" ]] && return 0  # placeholder text from CREDENTIALS.md table

  if grep -q "^${key}=" "$env_file"; then
    # use | as delimiter to avoid clashes with / in URLs
    sed -i "s|^${key}=.*|${key}=${value}|" "$env_file"
  else
    echo "${key}=${value}" >> "$env_file"
  fi
}

# ─── Sync AI-generated credentials (PostgreSQL / PgBouncer / Valkey / MinIO / pgAdmin / Auth) ───
echo ""
echo "─── Syncing AI-generated credentials ───"
for env in dev staging prod; do
  envfile=".env.$env"
  [ ! -f "$envfile" ] && continue

  # PostgreSQL: cols are | DB Name | Username | Password | Host | Port |
  db_user=$(table_row_field "## 🗄️ PostgreSQL" "$env" 2)
  db_pass=$(table_row_field "## 🗄️ PostgreSQL" "$env" 3)
  update_env "$envfile" "DB_USER" "$db_user"
  update_env "$envfile" "DB_PASSWORD" "$db_pass"

  # PgBouncer: cols are | Auth Password | Port |
  pgb_pass=$(table_row_field "## 🔀 PgBouncer" "$env" 1)
  update_env "$envfile" "PGBOUNCER_AUTH_PASSWORD" "$pgb_pass"

  # Valkey: cols are | Password | Port |
  redis_pass=$(table_row_field "## ⚡ Valkey" "$env" 1)
  update_env "$envfile" "REDIS_PASSWORD" "$redis_pass"

  # MinIO: cols are | Access Key | Secret Key | Port |
  minio_ak=$(table_row_field "## 🗂️ MinIO" "$env" 1)
  minio_sk=$(table_row_field "## 🗂️ MinIO" "$env" 2)
  update_env "$envfile" "STORAGE_ACCESS_KEY" "$minio_ak"
  update_env "$envfile" "STORAGE_SECRET_KEY" "$minio_sk"

  # pgAdmin: cols are | Login Email | Password | Port |
  pga_email=$(table_row_field "## 🖥️ pgAdmin" "$env" 1)
  pga_pass=$(table_row_field "## 🖥️ pgAdmin" "$env" 2)
  update_env "$envfile" "PGADMIN_EMAIL" "$pga_email"
  update_env "$envfile" "PGADMIN_PASSWORD" "$pga_pass"

  # Auth: cols are | AUTH_SECRET |
  auth_secret=$(table_row_field "## 🔐 Auth Secrets" "$env" 1)
  update_env "$envfile" "AUTH_SECRET" "$auth_secret"

  echo "  ✅ .env.$env credentials synced"
done

# ─── Sync SMTP (staging + prod only — dev uses MailHog) ─────────────
echo ""
echo "─── Syncing SMTP (staging + prod only — dev uses MailHog) ───"
extract_kv() {
  # extract the value from a `| Field | Value |` row by Field name
  local field="$1"
  grep "^| $field" "$CREDS" 2>/dev/null | head -1 | awk -F'|' '{print $3}' | sed 's/^ *//;s/ *$//' || echo ""
}
for env in staging prod; do
  envfile=".env.$env"
  [ ! -f "$envfile" ] && continue
  update_env "$envfile" "SMTP_HOST"      "$(extract_kv 'SMTP Host')"
  update_env "$envfile" "SMTP_PORT"      "$(extract_kv 'SMTP Port')"
  update_env "$envfile" "SMTP_USER"      "$(extract_kv 'Username')"
  update_env "$envfile" "SMTP_PASSWORD"  "$(extract_kv 'Password' | head -1)"
  update_env "$envfile" "SMTP_FROM"      "$(extract_kv 'From address')"
  update_env "$envfile" "SMTP_FROM_NAME" "$(extract_kv 'From name')"
done

# ─── Sync Xendit (only when payment.gateway: xendit in inputs.yml) ──
echo ""
echo "─── Syncing Xendit ───"
update_env ".env.dev"     "XENDIT_SECRET_KEY"    "$(extract_kv 'Secret API Key (TEST)')"
update_env ".env.dev"     "XENDIT_PUBLIC_KEY"    "$(extract_kv 'Public API Key (TEST)')"
update_env ".env.dev"     "XENDIT_WEBHOOK_TOKEN" "$(extract_kv 'Webhook Verification Token')"
for env in staging prod; do
  update_env ".env.$env" "XENDIT_SECRET_KEY"    "$(extract_kv 'Secret API Key (LIVE)')"
  update_env ".env.$env" "XENDIT_PUBLIC_KEY"    "$(extract_kv 'Public API Key (LIVE)')"
  update_env ".env.$env" "XENDIT_WEBHOOK_TOKEN" "$(extract_kv 'Webhook Verification Token')"
done

# ─── Sync Turnstile prod live keys (dev/staging keep test keys) ─────
echo ""
echo "─── Syncing Turnstile prod live keys ───"
update_env ".env.prod" "NEXT_PUBLIC_TURNSTILE_SITE_KEY" "$(extract_kv 'Site Key (LIVE)')"
update_env ".env.prod" "TURNSTILE_SECRET_KEY"           "$(extract_kv 'Secret Key (LIVE)')"

# ─── Sync Komodo UI URL ─────────────────────────────────────────────
echo ""
echo "─── Syncing Komodo ───"
for env in staging prod; do
  update_env ".env.$env" "KOMODO_UI_URL" "$(extract_kv 'Komodo UI URL')"
done

# ─── Sync Third-Party API Keys (read each row from the table) ──────
echo ""
echo "─── Syncing Third-Party API Keys ───"
{ awk '/^## 🔑 Third-Party/,/^---$/' "$CREDS" | grep -E "^\| [A-Z][A-Z0-9_]+" || true; } | while IFS='|' read -r _ service key value envs _; do
  key=$(echo "$key" | sed 's/^ *//;s/ *$//')
  value=$(echo "$value" | sed 's/^ *//;s/ *$//')
  envs=$(echo "$envs" | sed 's/^ *//;s/ *$//')

  [[ "$value" == *"⏳"* ]] && continue
  [ -z "$value" ] && continue
  [ -z "$key" ] && continue

  if [ "$envs" = "all" ]; then
    target_envs="dev staging prod"
  else
    target_envs=$(echo "$envs" | tr '/' ' ' | tr ',' ' ')
  fi

  for env in $target_envs; do
    update_env ".env.${env}" "$key" "$value"
  done
done

echo ""
echo "✅ Sync complete."
echo "   Run 'pnpm tools:check-env' (after Phase 4) to verify env files pass validation."
echo "   If CREDENTIALS.md still has ⏳ placeholders, Phase 5 pre-flight will list them."
