import { useState } from "react";

const C={abyss:"#050507",carbon:"#101010",wb:"#3d3a39",sig:"#00d992",mint:"#2fd6a1",snow:"#f2f2f2",parch:"#b8b3b0",slate:"#8b949e",quat:"#5c5855",danger:"#fb565b",warn:"#ffba00",warnP:"#ffdd80",ok:"#10b981",purp:"#818cf8"};

const SP=({s})=>{const m={Paid:{bg:"rgba(16,185,129,0.12)",c:C.ok},Active:{bg:"rgba(16,185,129,0.12)",c:C.ok},Completed:{bg:"rgba(16,185,129,0.12)",c:C.ok},Approved:{bg:"rgba(16,185,129,0.12)",c:C.ok},Fulfilled:{bg:"rgba(16,185,129,0.12)",c:C.ok},Received:{bg:"rgba(16,185,129,0.12)",c:C.ok},Released:{bg:"rgba(16,185,129,0.12)",c:C.ok},Resolved:{bg:"rgba(16,185,129,0.12)",c:C.ok},Delivered:{bg:"rgba(16,185,129,0.12)",c:C.ok},Closed:{bg:"rgba(139,148,158,0.12)",c:C.slate},Open:{bg:"rgba(0,217,146,0.12)",c:C.sig},Trial:{bg:"rgba(0,217,146,0.12)",c:C.sig},Published:{bg:"rgba(0,217,146,0.12)",c:C.sig},"In Progress":{bg:"rgba(0,217,146,0.12)",c:C.sig},"In Repair":{bg:"rgba(0,217,146,0.12)",c:C.sig},Processing:{bg:"rgba(0,217,146,0.12)",c:C.sig},Pending:{bg:"rgba(255,186,0,0.12)",c:C.warn},Draft:{bg:"rgba(255,186,0,0.12)",c:C.warn},"Partially Paid":{bg:"rgba(255,186,0,0.12)",c:C.warn},"Partially Fulfilled":{bg:"rgba(255,186,0,0.12)",c:C.warn},"Partially Recovered":{bg:"rgba(255,186,0,0.12)",c:C.warn},Paused:{bg:"rgba(255,186,0,0.12)",c:C.warn},Diagnosis:{bg:"rgba(255,186,0,0.12)",c:C.warn},Testing:{bg:"rgba(255,186,0,0.12)",c:C.warn},"Ready for Pickup":{bg:"rgba(0,217,146,0.12)",c:C.sig},"Quotation Pending":{bg:"rgba(255,186,0,0.12)",c:C.warn},"Past Due":{bg:"rgba(251,86,91,0.12)",c:C.danger},Overdue:{bg:"rgba(251,86,91,0.12)",c:C.danger},Suspended:{bg:"rgba(251,86,91,0.12)",c:C.danger},Cancelled:{bg:"rgba(251,86,91,0.12)",c:C.danger},Rejected:{bg:"rgba(251,86,91,0.12)",c:C.danger},Critical:{bg:"rgba(251,86,91,0.12)",c:C.danger},High:{bg:"rgba(255,186,0,0.12)",c:C.warn},Medium:{bg:"rgba(139,148,158,0.12)",c:C.slate},Low:{bg:"rgba(139,148,158,0.12)",c:C.slate},Government:{bg:"rgba(129,140,248,0.12)",c:C.purp},Private:{bg:"rgba(0,217,146,0.12)",c:C.sig},Individual:{bg:"rgba(139,148,158,0.12)",c:C.slate},Debit:{bg:"rgba(251,86,91,0.12)",c:C.danger},Credit:{bg:"rgba(16,185,129,0.12)",c:C.ok},Physical:{bg:"rgba(139,148,158,0.12)",c:C.slate},Service:{bg:"rgba(129,140,248,0.12)",c:C.purp},Yes:{bg:"rgba(0,217,146,0.12)",c:C.sig},No:{bg:"rgba(139,148,158,0.12)",c:C.slate},"E-Commerce":{bg:"rgba(129,140,248,0.12)",c:C.purp},Direct:{bg:"rgba(0,217,146,0.12)",c:C.sig},In:{bg:"rgba(16,185,129,0.12)",c:C.ok},Out:{bg:"rgba(251,86,91,0.12)",c:C.danger},Adjustment:{bg:"rgba(255,186,0,0.12)",c:C.warn},Transfer:{bg:"rgba(129,140,248,0.12)",c:C.purp},Regular:{bg:"rgba(139,148,158,0.12)",c:C.slate},VIP:{bg:"rgba(255,186,0,0.15)",c:C.warn},Dealer:{bg:"rgba(129,140,248,0.12)",c:C.purp},Online:{bg:"rgba(129,140,248,0.12)",c:C.purp},"In Store":{bg:"rgba(0,217,146,0.12)",c:C.sig}};const v=m[s]||{bg:"rgba(139,148,158,0.12)",c:C.slate};return<span style={{display:"inline-flex",padding:"2px 10px",borderRadius:9999,fontSize:11,fontWeight:600,background:v.bg,color:v.c,border:`1px solid ${v.c}33`,whiteSpace:"nowrap"}}>{s}</span>};

const KPI=({l,v,s,a})=><div style={{background:C.carbon,border:`1px solid ${C.wb}`,borderRadius:8,padding:"18px 22px",flex:1,minWidth:170}}><div style={{fontSize:11,color:C.slate,fontWeight:500,marginBottom:6}}>{l}</div><div style={{fontSize:24,fontWeight:700,color:a?C.sig:C.snow,fontFamily:"system-ui"}}>{v}</div>{s&&<div style={{fontSize:11,color:C.parch,marginTop:4}}>{s}</div>}</div>;

const T=({c,r})=><div style={{overflowX:"auto",border:`1px solid ${C.wb}`,borderRadius:8}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr style={{borderBottom:`1px solid ${C.wb}`}}>{c.map((h,i)=><th key={i} style={{padding:"9px 12px",textAlign:"left",color:C.slate,fontWeight:500,fontSize:11,whiteSpace:"nowrap"}}>{h}</th>)}</tr></thead><tbody>{r.map((row,ri)=><tr key={ri} style={{borderBottom:"1px solid rgba(61,58,57,0.5)"}} onMouseEnter={e=>e.currentTarget.style.background="rgba(255,255,255,0.02)"} onMouseLeave={e=>e.currentTarget.style.background="transparent"}>{row.map((cell,ci)=><td key={ci} style={{padding:"9px 12px",color:C.snow,whiteSpace:"nowrap"}}>{cell}</td>)}</tr>)}</tbody></table></div>;

const B=({children,p,o})=><button onClick={o} style={{background:C.carbon,color:p?C.mint:C.parch,border:`1px solid ${p?C.sig:C.wb}`,borderRadius:6,padding:"7px 14px",fontSize:13,fontWeight:500,cursor:"pointer"}}>{children}</button>;
const H=({t,s,children})=><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:22,flexWrap:"wrap",gap:8}}><h1 style={{fontSize:22,fontWeight:700,color:C.snow,fontFamily:"system-ui",margin:0}}>{t}</h1><div style={{display:"flex",gap:8,alignItems:"center"}}>{children}</div></div>;
const I=({t})=><div style={{background:"rgba(0,217,146,0.06)",border:"1px solid rgba(0,217,146,0.2)",borderRadius:8,padding:12,marginTop:14,fontSize:12,color:C.mint}}>💡 {t}</div>;
const P=({t})=><div style={{marginTop:10,fontSize:12,color:C.slate}}>{t}</div>;

const NAV=[
{l:"MAIN",items:[{id:"dashboard",n:"Dashboard"}]},
{l:"CRM / SALES",items:[{id:"customers",n:"Customers"},{id:"proposals",n:"Proposals & Quotations"},{id:"invoices",n:"Invoices"},{id:"subscriptions",n:"Subscriptions"}]},
{l:"PURCHASING",items:[{id:"vendors",n:"Vendors"},{id:"purchase-orders",n:"Purchase Orders"},{id:"goods-receipts",n:"Goods Receipts"}]},
{l:"INVENTORY",items:[{id:"products",n:"Products"},{id:"stock-movements",n:"Stock Movements"},{id:"disbursements",n:"Disbursements"},{id:"warehouses",n:"Warehouses"}]},
{l:"PROJECTS",items:[{id:"projects",n:"Projects"}]},
{l:"TASKS",items:[{id:"tasks",n:"Tasks (Kanban)"}]},
{l:"HR & PAYROLL",items:[{id:"employees",n:"Employees"},{id:"attendance",n:"Attendance / DTR"},{id:"leave",n:"Leave Requests"},{id:"cash-advances",n:"Cash Advances"},{id:"payroll",n:"Payroll"}]},
{l:"BANKING & FINANCE",items:[{id:"fund-sources",n:"Fund Sources"},{id:"transactions",n:"Transactions"},{id:"credit-cards",n:"Credit Card Payments"},{id:"fund-transfers",n:"Fund Transfers"},{id:"fund-requests",n:"Fund Requests"},{id:"master-ledger",n:"Master Ledger"}]},
{l:"ACCOUNTING",items:[{id:"chart-accounts",n:"Chart of Accounts"},{id:"journal-entries",n:"Journal Entries"},{id:"reports",n:"Reports"}]},
{l:"E-COMMERCE",items:[{id:"shop",n:"Storefront Preview"},{id:"ecom-orders",n:"Order Management"}]},
{l:"REPAIRS",items:[{id:"job-orders",n:"Job Orders"}]},
{l:"SUPPORT",items:[{id:"tickets",n:"Tickets"}]},
{l:"POS",items:[{id:"pos",n:"POS Terminal"}]},
{l:"CUSTOMER PORTAL",items:[{id:"portal-dash",n:"Portal Dashboard"},{id:"portal-orders",n:"Portal Orders"},{id:"portal-invoices",n:"Portal Invoices"},{id:"portal-proposals",n:"Portal Proposals"},{id:"portal-repairs",n:"Portal Repairs"},{id:"portal-projects",n:"Portal Projects"},{id:"portal-subs",n:"Portal Subscriptions"},{id:"portal-payments",n:"Portal Payments"},{id:"portal-tickets",n:"Portal Tickets"},{id:"portal-docs",n:"Portal Documents"},{id:"portal-profile",n:"Portal Profile"}]},
{l:"SETTINGS",items:[{id:"settings",n:"Tenant Settings"},{id:"users",n:"Users"},{id:"departments",n:"Departments"},{id:"expense-cats",n:"Expense Categories"},{id:"smtp",n:"SMTP Config"}]},
{l:"PLATFORM ADMIN",items:[{id:"pa-tenants",n:"Tenants"},{id:"pa-plans",n:"Plans"},{id:"pa-billing",n:"Billing"},{id:"pa-dlq",n:"DLQ Monitor"},{id:"pa-audit",n:"Audit Log"}]},
];

export default function App(){const[sc,setSc]=useState("dashboard");const[sb,setSb]=useState(true);

const R=()=>{switch(sc){

case"dashboard":return<div><H t="Task Dashboard"/><div style={{fontSize:13,color:C.slate,marginBottom:18}}>Welcome back, Bonito · Tenant Super Admin</div><div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:20}}><KPI l="Invoices Awaiting" v="12" s="₱847,250"/><KPI l="Projects Active" v="5"/><KPI l="Tasks Open" v="23" s="7 overdue"/><KPI l="Pending Approvals" v="4" s="2 disb · 1 exp · 1 fund req" a/></div><div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:20}}><KPI l="Fund Sources" v="₱2.59M"/><KPI l="CC Outstanding" v={<span style={{color:C.danger}}>₱186,500</span>}/><KPI l="E-Com Orders Today" v="3" s="₱28,400" a/><KPI l="Job Orders Open" v="5" s="2 ready for pickup"/></div><h2 style={{fontSize:15,fontWeight:600,color:C.snow,marginBottom:10}}>My Tasks</h2><div style={{display:"flex",gap:14}}>{[{t:"To Do",ts:[{n:"Install switches — Metro Aquatics",p:"High"},{n:"Quotation — PLDT fiber",p:"Medium"},{n:"Review PO shipping",p:"Low"}]},{t:"In Progress",ts:[{n:"Configure Cisco 2960X — Alaska Milk",p:"High"},{n:"Site survey Jollibee",p:"Medium"}]},{t:"Done",ts:[{n:"Deliver UPS to SMC",p:"Medium"}]}].map(col=><div key={col.t} style={{flex:1,background:C.carbon,border:`1px solid ${C.wb}`,borderRadius:8,padding:14}}><div style={{fontSize:12,fontWeight:600,color:C.slate,marginBottom:10}}>{col.t} ({col.ts.length})</div>{col.ts.map((tk,i)=><div key={i} style={{background:C.abyss,border:`1px solid ${C.wb}`,borderRadius:6,padding:10,marginBottom:6}}><div style={{fontSize:13,color:C.snow,marginBottom:4}}>{tk.n}</div><SP s={tk.p}/></div>)}</div>)}</div></div>;

case"customers":return<div><H t="Customers"><B p>+ New Customer</B></H><T c={["Company","Type","Tier","Contact","Credit Bal","Status"]} r={[["Metro Aquatics Inc.",<SP s="Private"/>,<SP s="VIP"/>,"Engr. Ramon Cruz","₱45,000",<SP s="Active"/>],["Alaska Milk Corp.",<SP s="Private"/>,<SP s="Regular"/>,"Maria Santos","₱0",<SP s="Active"/>],["DepEd Region IV-A",<SP s="Government"/>,<SP s="Regular"/>,"Dr. Elena Reyes","₱120,000",<SP s="Active"/>],["Jollibee Foods",<SP s="Private"/>,<SP s="VIP"/>,"Paolo Villanueva","₱0",<SP s="Active"/>],["San Miguel Corp.",<SP s="Private"/>,<SP s="Regular"/>,"Jenny Reyes","₱85,500",<SP s="Active"/>],["PLDT Enterprise",<SP s="Private"/>,<SP s="Dealer"/>,"Engr. Mark Gonzales","₱0",<SP s="Active"/>],["Juan dela Cruz",<SP s="Individual"/>,<SP s="Regular"/>,"—","₱0",<SP s="Active"/>],["Universal Robina",<SP s="Private"/>,<SP s="VIP"/>,"Rhea Aquino","₱32,000",<SP s="Active"/>],["Municipality of Lipa",<SP s="Government"/>,<SP s="Regular"/>,"Hon. Oscar Torres","₱0",<SP s="Pending"/>],["BDO Lipa",<SP s="Private"/>,<SP s="Regular"/>,"Carlo Tan","₱0",<SP s="Active"/>],["Batangas Medical",<SP s="Government"/>,<SP s="Regular"/>,"Dr. Ana D.","₱15,000",<SP s="Active"/>],["Converge ICT",<SP s="Private"/>,<SP s="Dealer"/>,"Kevin Lim","₱0",<SP s="Active"/>],["Globe SME",<SP s="Private"/>,<SP s="Regular"/>,"Rica Mendoza","₱8,200",<SP s="Active"/>],["Smart Comms",<SP s="Private"/>,<SP s="Regular"/>,"Nico Ramos","₱0",<SP s="Active"/>]]}/><P t="1-14 of 47 · Tiers: Regular (SRP), VIP (10% off), Dealer (12% off)"/></div>;

case"proposals":return<div><H t="Proposals & Quotations"><B p>+ Proposal</B><B>+ Quotation</B></H><T c={["Ref","Type","Title","Customer","Linked","Total","Rev","Status"]} r={[["PROP-0034","Proposal","Network Overhaul Ph2","Metro Aquatics","—","—","3",<SP s="Approved"/>],["QUO-0078","Quotation","Network Equipment","Metro Aquatics","PROP-34","₱485K","5",<SP s="Approved"/>],["PROP-0033","Proposal","CCTV 64-Cam Upgrade","Alaska Milk","—","—","1",<SP s="Draft"/>],["QUO-0077","Quotation","CCTV Hardware","Alaska Milk","PROP-33","₱328K","2",<SP s="Pending"/>],["QUO-0076","Quotation","Cat6A Bulk","San Miguel","—","₱67.8K","1",<SP s="Approved"/>],["PROP-0032","Proposal","IT Lab 40 Units","DepEd IV-A","—","—","2",<SP s="Approved"/>],["QUO-0075","Quotation","Lab Equipment","DepEd IV-A","PROP-32","₱1.25M","4",<SP s="Approved"/>],["QUO-0074","Quotation","Fiber Patches","PLDT","—","₱25.4K","1",<SP s="Pending"/>],["PROP-0031","Proposal","Server Room","URC","—","—","1",<SP s="In Progress"/>],["QUO-0073","Quotation","Server Hardware","URC","PROP-31","₱2.1M","3",<SP s="Draft"/>]]}/><I t="Golden formula: markedUpPrice = prevPrice / (1 - pct/100). Sections: Equipment, Materials, Labor."/></div>;

case"invoices":return<div><H t="Invoices"><B p>+ New Invoice</B></H><T c={["Invoice","Customer","Tier","Total","Paid","Credit","Balance","Status","Due"]} r={[["INV-0142","Metro Aquatics",<SP s="VIP"/>,"₱485K","₱200K","₱45K","₱240K",<SP s="Partially Paid"/>,"May 15"],["INV-0141","Alaska Milk",<SP s="Regular"/>,"₱128K","₱128K","₱0","₱0",<SP s="Paid"/>,"Apr 30"],["INV-0140","DepEd IV-A",<SP s="Regular"/>,"₱1.25M","₱0","₱120K","₱1.13M",<SP s="Pending"/>,"Jun 1"],["INV-0139","Jollibee",<SP s="VIP"/>,"₱345K","₱345K","₱0","₱0",<SP s="Paid"/>,"Apr 20"],["INV-0138","SMC",<SP s="Regular"/>,"₱67.8K","₱0","₱0","₱67.8K",<SP s="Overdue"/>,"Apr 15"],["INV-0137","PLDT",<SP s="Dealer"/>,"₱892K","₱446K","₱0","₱446K",<SP s="Partially Paid"/>,"May 10"],["INV-0136","Juan DC",<SP s="Regular"/>,"₱12.5K","₱12.5K","₱0","₱0",<SP s="Paid"/>,"Apr 18"],["INV-0135","URC",<SP s="VIP"/>,"₱2.1M","₱700K","₱32K","₱1.37M",<SP s="Partially Paid"/>,"Jun 15"],["INV-0134","Mun. Lipa",<SP s="Regular"/>,"₱560K","₱0","₱0","₱560K",<SP s="Draft"/>,"—"],["INV-0133","BDO Lipa",<SP s="Regular"/>,"₱45K","₱45K","₱0","₱0",<SP s="Paid"/>,"Apr 10"]]}/><P t="1-10 of 89 · VIP=10% disc · Dealer=12% disc · Regular=SRP"/></div>;

case"subscriptions":return<div><H t="Subscriptions"><B p>+ New</B></H><T c={["ID","Customer","Plan","Cycle","Monthly","Next Billing","Status"]} r={[["SUB-001","Metro Aquatics","Network Maint.","Monthly","₱15K","May 3",<SP s="Active"/>],["SUB-002","Alaska Milk","CCTV Monitor","Monthly","₱8.5K","May 1",<SP s="Active"/>],["SUB-003","Jollibee","POS Support","Quarterly","₱25K","Jun 15",<SP s="Active"/>],["SUB-004","PLDT","Fiber Maint.","Monthly","₱12K","May 5",<SP s="Active"/>],["SUB-005","San Miguel","IT Helpdesk","Monthly","₱20K","May 1",<SP s="Active"/>],["SUB-006","URC","Server Monitor","Monthly","₱35K","May 10",<SP s="Active"/>],["SUB-007","BDO Lipa","Annual Maint.","Annual","₱120K","Jan 2027",<SP s="Active"/>],["SUB-008","Smart","VoIP Support","Monthly","₱18K","May 8",<SP s="Paused"/>]]}/></div>;

case"vendors":return<div><H t="Vendors"><B p>+ New Vendor</B></H><T c={["Vendor","Type","Platform","Contact","POs","Status"]} r={[["Dataworld Direct",<SP s="Direct"/>,"—","Engr. Luis Ramos","12",<SP s="Active"/>],["Hikvision PH",<SP s="Direct"/>,"—","Anna Garcia","8",<SP s="Active"/>],["Ubiquiti PH",<SP s="Direct"/>,"—","Mark Tan","6",<SP s="Active"/>],["APC Philippines",<SP s="Direct"/>,"—","Beth Cruz","4",<SP s="Active"/>],["Cisco Gold PH",<SP s="Direct"/>,"—","James Lim","3",<SP s="Active"/>],["NetVille Solutions",<SP s="E-Commerce"/>,"Shopee","NetVille Store","15",<SP s="Active"/>],["CDR King",<SP s="E-Commerce"/>,"Lazada","CDR King Official","9",<SP s="Active"/>],["Cable Express",<SP s="E-Commerce"/>,"Shopee","Cable Express PH","7",<SP s="Active"/>],["MikroTik PH",<SP s="E-Commerce"/>,"TikTok Shop","MikroTik Official","3",<SP s="Active"/>],["TechTools PH",<SP s="E-Commerce"/>,"Shopee","TechTools Store","5",<SP s="Active"/>]]}/></div>;

case"purchase-orders":return<div><H t="Purchase Orders"><B p>+ New PO</B></H><T c={["PO","Vendor","Type","Items","Subtotal","Ship","Landed","Alloc","Status"]} r={[["PO-0089","NetVille (Shopee)",<SP s="E-Commerce"/>,"6","₱78.4K","₱1.25K","₱79.6K","4stk·2proj",<SP s="Received"/>],["PO-0088","CDR King (Lazada)",<SP s="E-Commerce"/>,"12","₱15.6K","₱0","₱15.6K","12 stk",<SP s="Pending"/>],["PO-0087","Dataworld",<SP s="Direct"/>,"8","₱245K","₱8.5K","₱253K","5stk·3proj",<SP s="In Progress"/>],["PO-0086","Hikvision",<SP s="Direct"/>,"20","₱70K","₱4.2K","₱74.2K","15stk·5co",<SP s="Received"/>],["PO-0085","MikroTik (TikTok)",<SP s="E-Commerce"/>,"3","₱37.5K","₱800","₱38.3K","3 stk",<SP s="Pending"/>],["PO-0084","Ubiquiti PH",<SP s="Direct"/>,"10","₱98K","₱6.3K","₱104K","8stk·2proj",<SP s="Approved"/>],["PO-0083","APC PH",<SP s="Direct"/>,"5","₱44.5K","₱3.8K","₱48.3K","3stk·2co",<SP s="Received"/>],["PO-0082","Cisco Gold",<SP s="Direct"/>,"4","₱104K","₱12.5K","₱116K","4 stk",<SP s="Draft"/>]]}/><I t="Ship cost dist: Equal Share (÷ qty) or Proportional by Cost (% value). Editable per item."/></div>;

case"goods-receipts":return<div><H t="Goods Receipts"/><T c={["GR","PO","Vendor","Rcvd","By","Date","Alloc Pend","Photos"]} r={[["GR-0045","PO-0089","NetVille","6/6","Maria Santos","Apr 28","0","3"],["GR-0044","PO-0087","Dataworld","5/8","Juan dela Cruz","Apr 27",<span style={{color:C.warn}}>3 pend</span>,"5"],["GR-0043","PO-0086","Hikvision","20/20","Rhea Aquino","Apr 26","0","4"],["GR-0042","PO-0083","APC PH","5/5","Paolo V.","Apr 25",<span style={{color:C.warn}}>2 pend</span>,"2"],["GR-0041","PO-0081","Cable Exp","50/50","Maria Santos","Apr 24","0","1"]]}/><I t="All items enter inventory first. System prompts allocation (project/company) after receipt."/></div>;

case"products":return<div><H t="Products"><B p>+ New Product</B></H><T c={["SKU","Product","Type","Cost","T1","T3 SRP","Stock","SN","E-Com","Status"]} r={[["PB-CBL-6A","Cat6A Cable 305m",<SP s="Physical"/>,"₱4.2K","₱4.9K","₱6.1K","45",<SP s="No"/>,<SP s="Yes"/>,<SP s="Active"/>],["PB-SW-2960X","Cisco 2960X-24",<SP s="Physical"/>,"₱26K","₱30.6K","₱38K","8",<SP s="Yes"/>,<SP s="Yes"/>,<SP s="Active"/>],["PB-RT-RB5009","MikroTik RB5009",<SP s="Physical"/>,"₱12.5K","₱14.7K","₱3K⌈","12",<SP s="Yes"/>,<SP s="Yes"/>,<SP s="Active"/>],["PB-UPS-1500","APC UPS 1500VA",<SP s="Physical"/>,"₱8.9K","₱10.5K","₱13K","3",<SP s="Yes"/>,<SP s="Yes"/>,<span style={{color:C.warn}}>⚠Low</span>],["PB-AP-U6P","Ubiquiti U6 Pro",<SP s="Physical"/>,"₱9.8K","₱11.5K","₱14.3K","15",<SP s="Yes"/>,<SP s="Yes"/>,<SP s="Active"/>],["PB-CAM-4MP","Hikvision 4MP",<SP s="Physical"/>,"₱3.5K","₱4.1K","₱5.1K","28",<SP s="Yes"/>,<SP s="Yes"/>,<SP s="Active"/>],["PB-RJ45-100","RJ45 Cat6 100pc",<SP s="Physical"/>,"₱450","₱529","₱659","120",<SP s="No"/>,<SP s="No"/>,<SP s="Active"/>],["PB-SVC-INST","Install/hr",<SP s="Service"/>,"₱500","₱588","₱732","—",<SP s="No"/>,<SP s="No"/>,<SP s="Active"/>],["PB-NVR-8CH","Hikvision NVR 8CH",<SP s="Physical"/>,"₱15.2K","₱17.9K","₱3K⌈","5",<SP s="Yes"/>,<SP s="Yes"/>,<SP s="Active"/>],["PB-RACK-42U","42U Server Rack",<SP s="Physical"/>,"₱28K","₱32.9K","₱3K⌈","2",<SP s="No"/>,<SP s="No"/>,<span style={{color:C.warn}}>⚠Low</span>]]}/><P t="1-10 of 156 · Cost: ₱4.3M · SRP: ₱6.0M · ⌈ = ceiling-capped · E-Com = shown on storefront"/></div>;

case"stock-movements":return<div><H t="Stock Movements"/><T c={["Date","Product","Type","Qty","Ref","Serials","Notes"]} r={[["Apr 28","APC UPS 1500VA",<SP s="In"/>,"5","GR-0042","SN-APC-001~005","PO APC PH"],["Apr 28","APC UPS 1500VA",<SP s="Out"/>,"2","DISB-0018","SN-APC-004,005","→ Metro Aquatics"],["Apr 27","Cisco 2960X",<SP s="In"/>,"4","GR-0044","SN-CSC-041~044","PO Dataworld"],["Apr 27","Cat6A Cable",<SP s="Out"/>,"10","POS-4521","—","POS sale"],["Apr 26","Hikvision 4MP",<SP s="In"/>,"20","GR-0043","SN-HIK-201~220","PO Hikvision"],["Apr 26","Ubiquiti U6",<SP s="Out"/>,"3","INV-0137","SN-UBQ-015~017","PLDT invoice"],["Apr 25","MikroTik RB5009",<SP s="Transfer"/>,"2","TRF-0008","SN-MK-089,090","Wh A→B"],["Apr 25","SC Fiber",<SP s="Adjustment"/>,"-2","ADJ-0015","—","Damaged"],["Apr 24","RJ45 Cat6",<SP s="Out"/>,"5","JO-20260424ABC","—","Job order parts"]]}/></div>;

case"disbursements":return<div><H t="Inventory Disbursements"><B p>+ Request</B></H><T c={["Disb","Project","By","Items","Cost","Approved","Status"]} r={[["DISB-0018","Metro Aquatics","Juan","3","₱42.5K","Bonito",<SP s="Fulfilled"/>],["DISB-0017","Office Upgrade","Maria","2","₱11.2K","Bonito",<SP s="Fulfilled"/>],["DISB-0016","DepEd Lab","Rhea","8","₱185K","—",<SP s="Pending"/>],["DISB-0015","PLDT Fiber","Paolo","5","₱68K","Bonito",<SP s="Partially Fulfilled"/>],["DISB-0014","Jollibee POS","Juan","4","₱34.5K","Bonito",<SP s="Fulfilled"/>]]}/><I t="4-step: Request → Approve → Scan/Fulfill → Expense at actual cost. No journal entry."/></div>;

case"warehouses":return<div><H t="Warehouses"><B p>+ New</B></H><T c={["Warehouse","Location","Products","Units","Default"]} r={[["Main Store Lipa","Brgy Marawoy, Lipa","142","4,850",<SP s="Yes"/>],["Warehouse B","Batangas City","38","620",<SP s="No"/>],["Project Staging","Powerbyte 2F","12","45",<SP s="No"/>]]}/></div>;

case"projects":return<div><H t="Projects"><B p>+ New Project</B></H><T c={["Project","Customer","Budget","Expenses","Invoiced","P/L","Tasks","Status"]} r={[["Network Overhaul","Metro Aquatics","₱800K","₱312K","₱485K",<span style={{color:C.ok}}>₱172K</span>,"12/18",<SP s="In Progress"/>],["CCTV 32-Cam","Alaska Milk","₱250K","₱187K","₱128K",<span style={{color:C.danger}}>-₱58K</span>,"8/8",<SP s="Completed"/>],["IT Lab 40","DepEd IV-A","₱2.0M","₱845K","₱1.25M",<span style={{color:C.ok}}>₱405K</span>,"5/22",<SP s="In Progress"/>],["POS Deploy","Jollibee","₱500K","₱289K","₱345K",<span style={{color:C.ok}}>₱56K</span>,"15/15",<SP s="Completed"/>],["Fiber Backbone","PLDT","₱1.5M","₱420K","₱892K",<span style={{color:C.ok}}>₱472K</span>,"8/30",<SP s="In Progress"/>],["Server Room","URC","₱3.5M","₱1.2M","₱2.1M",<span style={{color:C.ok}}>₱900K</span>,"20/45",<SP s="In Progress"/>],["WiFi Mesh","Batangas Med","₱350K","₱95K","₱178K",<span style={{color:C.ok}}>₱83K</span>,"3/10",<SP s="In Progress"/>],["Firewall","Globe SME","₱150K","₱42K","₱95K",<span style={{color:C.ok}}>₱53K</span>,"6/8",<SP s="In Progress"/>]]}/></div>;

case"tasks":return<div><H t="Tasks"><B>Calendar</B><B p>+ New Task</B></H><div style={{display:"flex",gap:14,overflowX:"auto"}}>{[{t:"To Do",c:C.warn,ts:["Install switches — Metro Aquatics","Quotation — PLDT fiber","Review PO shipping","Order UPS replacement"]},{t:"In Progress",c:C.sig,ts:["Configure Cisco 2960X","Site survey Jollibee","Run fiber Floor 2"]},{t:"Done",c:C.ok,ts:["Deliver UPS to SMC","Install 16 CCTV cams","Configure VoIP"]},{t:"Cancelled",c:C.danger,ts:["Procure rack Server Direct"]}].map(col=><div key={col.t} style={{minWidth:250,flex:1,background:C.carbon,border:`1px solid ${C.wb}`,borderRadius:8,padding:14}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:10}}><div style={{width:8,height:8,borderRadius:9999,background:col.c}}/><span style={{fontSize:13,fontWeight:600,color:C.snow}}>{col.t} ({col.ts.length})</span></div>{col.ts.map((n,i)=><div key={i} style={{background:C.abyss,border:`1px solid ${C.wb}`,borderRadius:6,padding:10,marginBottom:6,fontSize:13,color:C.snow}}>{n}</div>)}</div>)}</div></div>;

case"employees":return<div><H t="Employees"><B p>+ New</B></H><T c={["#","Name","Position","Dept","Type","Salary","Status"]} r={[["001","Bonito Aguileon","CEO","Mgmt","Full-time","₱80K",<SP s="Active"/>],["002","Maria Santos","Project Mgr","Ops","Full-time","₱45K",<SP s="Active"/>],["003","Juan dela Cruz","Sr. Tech","Tech","Full-time","₱35K",<SP s="Active"/>],["004","Rhea Aquino","Inventory","Warehouse","Full-time","₱28K",<SP s="Active"/>],["005","Paolo Villanueva","Field Tech","Tech","Full-time","₱30K",<SP s="Active"/>],["006","Jenny Reyes","Accountant","Finance","Full-time","₱40K",<SP s="Active"/>],["007","Carlo Tan","Sales","Sales","Full-time","₱25K",<SP s="Active"/>],["008","Rica Mendoza","HR Mgr","HR","Full-time","₱38K",<SP s="Active"/>],["009","Kevin Lim","Support","Support","Contract","₱22K",<SP s="Active"/>],["010","Beth Magno","Cashier","Store","Part-time","₱18K",<SP s="Active"/>]]}/></div>;

case"attendance":return<div><H t="Attendance / DTR"/><div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:18}}><KPI l="Present Today" v="8" s="of 10"/><KPI l="Pending" v="3" a/><KPI l="Offline Synced" v="2"/></div><T c={["Date","Employee","In","Location","GPS","Out","Hrs","Status"]} r={[["Apr 28","Maria Santos","8:02 AM","Office","14.31,121.16","5:05 PM","9.0",<SP s="Approved"/>],["Apr 28","Juan dela Cruz","7:45 AM","Project","14.30,121.15","—","—",<SP s="Pending"/>],["Apr 28","Rhea Aquino","8:15 AM","Office","14.31,121.16","5:00 PM","8.75",<SP s="Approved"/>],["Apr 28","Paolo V.","7:30 AM","Project","14.58,121.06","4:30 PM","9.0",<SP s="Pending"/>],["Apr 27","Juan dela Cruz","6:30 AM","Project",<span style={{color:C.warn}}>null GPS</span>,"4:00 PM","9.5",<SP s="Approved"/>]]}/></div>;

case"leave":return<div><H t="Leave Requests"/><T c={["ID","Employee","Type","Start","End","Days","By","Status"]} r={[["LR-042","Maria Santos","Vacation","May 5","May 9","5","Rica",<SP s="Approved"/>],["LR-041","Juan dela Cruz","Sick","Apr 25","Apr 25","1","Rica",<SP s="Approved"/>],["LR-040","Paolo V.","Emergency","Apr 22","Apr 23","2","Rica",<SP s="Approved"/>],["LR-039","Rhea Aquino","Vacation","May 12","May 16","5","—",<SP s="Pending"/>]]}/></div>;

case"cash-advances":return<div><H t="Cash Advances"><B p>+ New</B></H><T c={["ID","Employee","Amount","Purpose","Recovery","Status"]} r={[["CA-018","Juan","₱15K","Project materials","3/6",<SP s="Partially Recovered"/>],["CA-017","Paolo","₱8K","Transportation","6/6",<SP s="Completed"/>],["CA-016","Maria","₱20K","Emergency","1/4",<SP s="Partially Recovered"/>],["CA-015","Rhea","₱5K","Office supplies","—",<SP s="Approved"/>]]}/><I t="Personal loan deducted from salary. Different from custodian FundSource accounts."/></div>;

case"payroll":return<div><H t="Payroll"><B p>+ New Run</B></H><T c={["Pay #","Period","Emp","Gross","Deductions","CA","Net","Fund","Status"]} r={[["PAY-08","Apr 16-30","10","₱371K","₱52K","₱12.5K","₱306K","BDO",<SP s="Released"/>],["PAY-07","Apr 1-15","10","₱371K","₱52K","₱8K","₱310K","BDO",<SP s="Released"/>],["PAY-06","Mar 16-31","10","₱371K","₱52K","₱5K","₱313K","BDO",<SP s="Released"/>]]}/></div>;

case"fund-sources":return<div><H t="Fund Sources"><B p>+ New Account</B></H><div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:20}}>{[{n:"Main Store Cash",t:"Cash on Hand",b:"₱245,800",h:null,r:false},{n:"BDO Savings",t:"Bank",b:"₱1,850,000",h:null,r:false},{n:"UnionBank",t:"Bank",b:"₱420,090",h:null,r:false},{n:"GCash",t:"E-Wallet",b:"₱38,500",h:null,r:false},{n:"GoTyme",t:"E-Wallet",b:"₱15,200",h:null,r:false},{n:"BPI CC",t:"Credit Card",b:"₱186,500",h:null,r:true},{n:"Cash — Juan",t:"Custodian",b:"₱12,500",h:"Juan",r:false},{n:"Cash — Maria",t:"Custodian",b:"₱8,300",h:"Maria",r:false}].map((a,i)=><div key={i} style={{background:C.carbon,border:`1px solid ${a.r?"rgba(251,86,91,0.4)":C.wb}`,borderRadius:8,padding:18,minWidth:220,flex:1,cursor:"pointer"}} onClick={()=>setSc("transactions")}><div style={{fontSize:13,fontWeight:600,color:C.snow}}>{a.n}</div><div style={{fontSize:11,color:C.slate,marginBottom:8}}>{a.t}</div><div style={{fontSize:22,fontWeight:700,color:a.r?C.danger:C.snow,fontFamily:"system-ui"}}>{a.b}</div>{a.h&&<div style={{fontSize:11,color:C.parch,marginTop:4}}>Held by: {a.h}</div>}{a.r&&<div style={{fontSize:11,color:C.danger,marginTop:4}}>Outstanding liability</div>}</div>)}</div><div style={{background:C.carbon,border:`1px solid ${C.wb}`,borderRadius:8,padding:14}}><div style={{fontSize:11,color:C.slate}}>TOTAL REAL CASH</div><div style={{fontSize:26,fontWeight:700,color:C.sig,fontFamily:"system-ui"}}>₱2,590,390</div></div></div>;

case"transactions":return<div><H t="Ledger — BDO Savings"><B>Export</B></H><div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:18}}><KPI l="Balance" v="₱1,850,000"/><KPI l="Credits (Apr)" v="₱892,500"/><KPI l="Debits (Apr)" v="₱685,000"/></div><T c={["Date","Description","Type","Debit","Credit","Balance","Ref"]} r={[["Apr 28","Payment Alaska Milk",<SP s="Credit"/>,"","₱128.5K","₱1,850K","PAY-892"],["Apr 26","Payroll Apr 16-30",<SP s="Debit"/>,"₱306K","","₱1,721K","PAY-RUN-08"],["Apr 26","Payment PLDT",<SP s="Credit"/>,"","₱446K","₱2,027K","PAY-891"],["Apr 25","Transfer → Juan",<SP s="Debit"/>,"₱5K","","₱1,581K","TRF-045"],["Apr 24","CC installment 4/12",<SP s="Debit"/>,"₱9.3K","","₱1,586K","CCPAY-04"],["Apr 23","Cash advance Maria",<SP s="Debit"/>,"₱20K","","₱1,595K","CA-016"]]}/></div>;

case"credit-cards":return<div><H t="Credit Card — BPI"><B p>+ Payment</B></H><div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:18}}><KPI l="Outstanding" v={<span style={{color:C.danger}}>₱186,500</span>}/><KPI l="Limit" v="₱500,000"/><KPI l="Available" v="₱313,500"/><KPI l="Installments" v="2"/></div><h2 style={{fontSize:14,fontWeight:600,color:C.snow,marginBottom:10}}>Installments</h2><T c={["ID","Original","Monthly","Months","Paid","Interest","Remaining","Status"]} r={[["INST-001","₱100K","₱9.3K","12","4/12","₱11.6K","₱74.4K",<SP s="In Progress"/>],["INST-002","₱45K","₱4K","12","2/12","₱3K","₱40K",<SP s="In Progress"/>]]}/><h2 style={{fontSize:14,fontWeight:600,color:C.snow,margin:"16px 0 10px"}}>Recent Charges</h2><T c={["Date","Description","Amount"]} r={[["Apr 27","PO-0087 Dataworld",<span style={{color:C.danger}}>₱245,000</span>],["Apr 24","Office supplies Shopee",<span style={{color:C.danger}}>₱4,500</span>],["Apr 20","Fuel Shell Lipa",<span style={{color:C.danger}}>₱3,200</span>]]}/></div>;

case"fund-transfers":return<div><H t="Fund Transfers"><B p>+ Transfer</B></H><T c={["ID","From","To","Amount","Description","By","Date"]} r={[["TRF-045","BDO","Cash — Juan","₱5K","Project materials","Bonito","Apr 28"],["TRF-044","Main Store","BDO","₱50K","Daily deposit","Jenny","Apr 27"],["TRF-043","BDO","Cash — Maria","₱10K","Metro Aquatics exp","Bonito","Apr 26"],["TRF-042","Cash — Maria","Main Store","₱3.5K","Return unused","Maria","Apr 25"],["TRF-041","BDO","GCash","₱20K","Top-up couriers","Jenny","Apr 24"],["TRF-040","BDO","BPI CC","₱9.3K","CC installment","Jenny","Apr 24"]]}/></div>;

case"fund-requests":return<div><H t="Fund Requests"><B p>+ Request</B></H><T c={["ID","By","From","To","Amount","Purpose","Date","Status"]} r={[["FREQ-013","Juan","BDO","Cash—Juan","₱8K","Cable materials","Apr 28",<SP s="Pending"/>],["FREQ-012","Maria","GoTyme","Cash—Maria","₱10K","Transport PLDT","Apr 25",<SP s="Approved"/>],["FREQ-011","Paolo","Main Store","Cash—Paolo","₱3.5K","Hardware JFC","Apr 22",<SP s="Approved"/>],["FREQ-010","Rhea","BDO","Cash—Rhea","₱5K","Warehouse supplies","Apr 20",<SP s="Rejected"/>]]}/><I t="Any custodian can request. Account holder or admin approves. Auto-creates FundTransfer."/></div>;

case"master-ledger":return<div><H t="Master Ledger"><B>Export CSV</B></H><div style={{display:"flex",gap:8,marginBottom:14}}><input type="date" defaultValue="2026-04-01" style={{background:C.carbon,border:`1px solid ${C.wb}`,borderRadius:6,padding:"7px 10px",color:C.parch,fontSize:13}}/><span style={{color:C.slate,alignSelf:"center"}}>to</span><input type="date" defaultValue="2026-04-28" style={{background:C.carbon,border:`1px solid ${C.wb}`,borderRadius:6,padding:"7px 10px",color:C.parch,fontSize:13}}/><select style={{background:C.carbon,border:`1px solid ${C.wb}`,borderRadius:6,padding:"7px 10px",color:C.parch,fontSize:13}}><option>All Accounts</option></select></div><T c={["Date","Account","Type","Description","Debit","Credit","Balance","Ref"]} r={[["Apr 28","BDO",<SP s="Credit"/>,"Payment Alaska Milk","","₱128.5K","₱1,850K","PAY-892"],["Apr 28","Main Store",<SP s="Debit"/>,"Transfer → Juan","₱5K","","₱245.8K","TRF-045"],["Apr 28","Cash—Juan",<SP s="Credit"/>,"Transfer ← Main","","₱5K","₱12.5K","TRF-045"],["Apr 27","BPI CC",<SP s="Debit"/>,"PO Dataworld","₱245K","",<span style={{color:C.danger}}>₱186.5K</span>,"PO-087"],["Apr 27","GCash",<SP s="Debit"/>,"Lalamove PO-087","₱1.2K","","₱38.5K","SHIP-01"],["Apr 27","GCash",<SP s="Debit"/>,"Aguileon Cargo","₱3.8K","","₱39.7K","SHIP-02"],["Apr 27","Main Store",<SP s="Credit"/>,"POS Sale #4521","","₱15.8K","₱250.8K","POS-4521"],["Apr 27","Main Store",<SP s="Credit"/>,"E-Com Order #ORD-042","","₱14.3K","₱265.1K","ORD-042"],["Apr 26","Cash—Maria",<SP s="Debit"/>,"Transport Metro Aq","₱1.5K","","₱8.3K","EXP-234"],["Apr 26","BDO",<SP s="Debit"/>,"Payroll Apr 16-30","₱306K","","₱1,721K","PAY-08"],["Apr 26","UnionBank",<SP s="Credit"/>,"Payment PLDT","","₱446K","₱420K","PAY-891"],["Apr 25","Main Store",<SP s="Debit"/>,"Gasoline","₱3.5K","","₱235K","EXP-233"],["Apr 24","BPI CC",<SP s="Debit"/>,"Office supplies","₱4.5K","",<span style={{color:C.danger}}>₱142K</span>,"PO-086"],["Apr 24","BDO",<SP s="Debit"/>,"CC installment 4/12","₱9.3K","","₱2,006K","CCPAY-04"],["Apr 24","Main Store",<SP s="Credit"/>,"Xendit — JO-20260424 parts","","₱8.5K","₱238.5K","JO-PAY"]]}/><P t="1-15 of 385 · All accounts · Apr 1–28"/></div>;

case"chart-accounts":return<div><H t="Chart of Accounts"><B p>+ New</B></H><T c={["Code","Account","Type","Balance"]} r={[["1000","Cash & Equivalents","Asset","₱2,590,390"],["1100","Accounts Receivable","Asset","₱3,847,200"],["1200","Inventory","Asset","₱4,285,600"],["2000","Accounts Payable","Liability","₱186,500"],["2100","CC Payable","Liability","₱186,500"],["3000","Owner's Equity","Equity","₱8,500,000"],["4000","Sales Revenue","Income","₱5,892,400"],["4100","Service Revenue","Income","₱1,245,000"],["4200","E-Commerce Revenue","Income","₱428,000"],["5000","COGS","Expense","₱3,285,600"],["5100","Operating Expenses","Expense","₱845,000"],["5200","Salaries","Expense","₱2,226,000"],["5300","Bank Charges","Expense","₱14,600"]]}/></div>;

case"journal-entries":return<div><H t="Journal Entries"/><T c={["JE","Date","Description","Ref","Debit","Credit","By"]} r={[["JE-892","Apr 28","Payment Alaska Milk","PAY-892","₱128.5K","₱128.5K","Sys"],["JE-891","Apr 26","Payroll Apr 16-30","PAY-08","₱306K","₱306K","Sys"],["JE-890","Apr 26","Payment PLDT","PAY-891","₱446K","₱446K","Sys"],["JE-889","Apr 25","Gasoline","EXP-233","₱3.5K","₱3.5K","Jenny"],["JE-888","Apr 24","PO Dataworld","PO-087","₱245K","₱245K","Sys"],["JE-887","Apr 24","CC interest","CCPAY-04","₱966","₱966","Sys"],["JE-886","Apr 24","E-Com order Xendit","ORD-042","₱14.3K","₱14.3K","Sys"]]}/><I t="Auto-posted on every money movement. inventory_consumed excluded."/></div>;

case"reports":return<div><H t="Reports"/><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14}}>{[{n:"Income vs Expense",d:"Revenue vs operational expenses. POs excluded."},{n:"Master Ledger",d:"All txns, all accounts, chronological."},{n:"P&L Statement",d:"Profit & Loss. inventory_consumed excluded."},{n:"Balance Sheet",d:"Assets, liabilities, equity."},{n:"Cash Flow",d:"Inflows vs outflows by period."},{n:"Sales Report",d:"Revenue, customers, aging, MRR."},{n:"PO Report",d:"PO spending, vendor, allocations."},{n:"Inventory Valuation",d:"At cost ₱4.3M · At SRP ₱6.0M."},{n:"Project Profitability",d:"Revenue vs actual cost per project."},{n:"E-Commerce Sales",d:"Online orders, payment methods, conversion."},{n:"Job Order Report",d:"Repair volume, aging, parts cost."},{n:"Fund Accounts",d:"Per-account ledger, custodian balances."}].map((r,i)=><div key={i} style={{background:C.carbon,border:`1px solid ${C.wb}`,borderRadius:8,padding:18,cursor:"pointer"}} onMouseEnter={e=>e.currentTarget.style.borderColor=C.sig} onMouseLeave={e=>e.currentTarget.style.borderColor=C.wb}><div style={{fontSize:13,fontWeight:600,color:C.snow,marginBottom:4}}>{r.n}</div><div style={{fontSize:12,color:C.parch}}>{r.d}</div></div>)}</div></div>;

// ═══ E-COMMERCE ═══
case"shop":return<div><H t="E-Commerce Storefront Preview"><B p>Manage Products</B></H><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}>{[{n:"Cisco 2960X-24",p:"₱38,064",img:"🔌",s:8},{n:"MikroTik RB5009",p:"₱3,000⌈",img:"📡",s:12},{n:"APC UPS 1500VA",p:"₱13,030",img:"🔋",s:3},{n:"Ubiquiti U6 Pro",p:"₱14,348",img:"📶",s:15},{n:"Hikvision 4MP Dome",p:"₱5,124",img:"📷",s:28},{n:"Cat6A Cable 305m",p:"₱6,148",img:"🔗",s:45},{n:"Hikvision NVR 8CH",p:"₱3,000⌈",img:"💾",s:5},{n:"SFP+ 10G SR",p:"₱4,100",img:"⚡",s:18}].map((p,i)=><div key={i} style={{background:C.carbon,border:`1px solid ${C.wb}`,borderRadius:8,padding:16,textAlign:"center"}}><div style={{fontSize:40,marginBottom:8}}>{p.img}</div><div style={{fontSize:13,fontWeight:600,color:C.snow,marginBottom:4}}>{p.n}</div><div style={{fontSize:18,fontWeight:700,color:C.sig,fontFamily:"system-ui"}}>{p.p}</div><div style={{fontSize:11,color:C.slate,marginTop:4}}>{p.s} in stock</div><div style={{marginTop:8}}><B p>Add to Cart</B></div></div>)}</div><I t="Only products with isVisibleInEcommerce = true shown. Checkout requires login. Xendit payment (GCash/Maya/Card/Bank). Customer tier discount applied automatically."/></div>;

case"ecom-orders":return<div><H t="E-Commerce Order Management"/><div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:18}}><KPI l="Orders Today" v="3" s="₱28,400" a/><KPI l="Pending Payment" v="1"/><KPI l="Processing" v="2"/><KPI l="This Month Revenue" v="₱428,000"/></div><T c={["Order","Customer","Tier","Type","Items","Total","Discount","Payment","Xendit","Status"]} r={[["ORD-042","Metro Aquatics",<SP s="VIP"/>,<SP s="Online"/>,"2","₱14,348","10%","GCash","xnd_123",<SP s="Processing"/>],["ORD-041","Juan dela Cruz",<SP s="Regular"/>,<SP s="In Store"/>,"3","₱8,200","—","Cash","—",<SP s="Completed"/>],["ORD-040","PLDT Enterprise",<SP s="Dealer"/>,<SP s="Online"/>,"5","₱71,740","12%","Bank Txfr","xnd_122",<SP s="Delivered"/>],["ORD-039","Alaska Milk",<SP s="Regular"/>,<SP s="Online"/>,"1","₱5,124","—","Maya","xnd_121",<SP s="Paid"/>],["ORD-038","Converge ICT",<SP s="Dealer"/>,<SP s="Online"/>,"4","₱24,592","12%","CC Visa","xnd_120",<SP s="Completed"/>],["ORD-037","Globe SME",<SP s="Regular"/>,<SP s="Online"/>,"2","₱19,472","5%*","GCash","xnd_119",<SP s="Pending"/>]]}/><P t="* = Regular 5% discount on ≥₱3K, subject to admin approval"/></div>;

// ═══ JOB ORDERS ═══
case"job-orders":return<div><H t="Repairs & Job Orders"><B p>+ New Job Order</B></H><div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:18}}><KPI l="Open Jobs" v="5"/><KPI l="Ready for Pickup" v="2" a/><KPI l="Avg Days in Shop" v="3.2"/><KPI l="Parts Cost (Apr)" v="₱42,500"/></div><T c={["Job Order ID","Customer","Device","Brand/Model","Issue","Tech","Parts","Status"]} r={[["20260428HKWM3R","Metro Aquatics","Router","MikroTik RB5009","No internet output","Juan",<SP s="Yes"/>,<SP s="In Repair"/>],["20260427LPQ8NV","Juan dela Cruz","Laptop","Dell Latitude 5520","Screen flickering","Paolo",<SP s="No"/>,<SP s="Diagnosis"/>],["20260426XRTM2F","Alaska Milk","NVR","Hikvision DS-7608","HDD failure","Juan",<SP s="Yes"/>,<SP s="Quotation Pending"/>],["20260425BNWK9D","Jollibee Foods","POS Terminal","Custom Build","Receipt printer jam","Paolo",<SP s="No"/>,<SP s="Ready for Pickup"/>],["20260424FRTJ5L","BDO Lipa","UPS","APC BX1500","Battery not holding","Juan",<SP s="Yes"/>,<SP s="Testing"/>],["20260423WMVK8P","San Miguel","AP","Ubiquiti U6 Pro","Intermittent WiFi","Paolo",<SP s="No"/>,<SP s="Ready for Pickup"/>],["20260420QLNR3V","Globe SME","Firewall","Cisco ASA","Config error — resolved","Juan",<SP s="No"/>,<SP s="Released"/>],["20260418PXWM6K","PLDT Enterprise","Switch","Cisco 2960X","Port 12 dead — replaced","Juan",<SP s="Yes"/>,<SP s="Closed"/>]]}/><I t="14-char Job Order ID: YYYYMMDD + 6 random. Printable PDF with signatures. Parts use Quotation markup computation."/></div>;

// ═══ SUPPORT ═══
case"tickets":return<div><H t="Tickets"><B p>+ New</B></H><T c={["#","Subject","Customer","Priority","Assigned","Created","Status"]} r={[["TKT-089","Internet intermittent","Metro Aquatics",<SP s="Critical"/>,"Juan","Apr 28",<SP s="Open"/>],["TKT-088","CCTV Cam 12 offline","Alaska Milk",<SP s="High"/>,"Paolo","Apr 27",<SP s="In Progress"/>],["TKT-087","POS not printing","Jollibee",<SP s="Medium"/>,"Juan","Apr 26",<SP s="In Progress"/>],["TKT-086","WiFi dead zone ER","Batangas Med",<SP s="High"/>,"Maria","Apr 25",<SP s="Open"/>],["TKT-085","VPN access req","PLDT",<SP s="Low"/>,"Kevin","Apr 24",<SP s="Resolved"/>],["TKT-084","Invoice query","URC",<SP s="Low"/>,"Carlo","Apr 23",<SP s="Closed"/>]]}/></div>;

// ═══ POS ═══
case"pos":return<div><H t="POS Terminal"/><div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:18}}><KPI l="Session" v="POS-4522" s="8:00 AM"/><KPI l="Opening Cash" v="₱10,000"/><KPI l="Sales Today" v="₱45,300" s="8 txns" a/><KPI l="Fund" v="Main Store"/></div><div style={{display:"flex",gap:20}}><div style={{flex:2}}><T c={["Product","Qty","Price","SN","Subtotal"]} r={[["Cat6A Cable 305m","2","₱6,148","—","₱12,296"],["RJ45 Cat6 100pc","5","₱659","—","₱3,295"],["Ubiquiti U6 Pro","1","₱14,348",<span style={{color:C.warn}}>⚠ Scan</span>,"₱14,348"]]}/><div style={{textAlign:"right",marginTop:14}}><div style={{fontSize:13,color:C.slate}}>Subtotal: ₱29,939 · VAT: ₱3,593</div><div style={{fontSize:22,fontWeight:700,color:C.sig,fontFamily:"system-ui"}}>₱33,532</div></div><div style={{display:"flex",gap:8,marginTop:10}}><B p>Pay</B><B>Clear</B><B>Link Customer</B></div></div><div style={{flex:1}}><input placeholder="Scan barcode or search..." style={{width:"100%",background:C.carbon,border:`1px solid ${C.wb}`,borderRadius:6,padding:"10px 12px",color:C.snow,fontSize:13}}/></div></div></div>;

// ═══ CUSTOMER PORTAL ═══
case"portal-dash":return<div><H t="Customer Portal — Dashboard"/><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:18}}><div style={{fontSize:16,fontWeight:600,color:C.snow}}>Welcome, Engr. Ramon Cruz</div><SP s="VIP"/></div><div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:18}}><KPI l="Outstanding Balance" v="₱240,000"/><KPI l="Open Orders" v="1" a/><KPI l="Repairs in Shop" v="1"/><KPI l="Credit Balance" v="₱45,000"/></div><h2 style={{fontSize:14,fontWeight:600,color:C.snow,marginBottom:10}}>Recent Activity</h2><T c={["Date","Activity","Details","Status"]} r={[["Apr 28","E-Commerce Order","ORD-042 — Ubiquiti U6 Pro",<SP s="Processing"/>],["Apr 28","Job Order Update","20260428HKWM3R — MikroTik repair in progress",<SP s="In Repair"/>],["Apr 27","Invoice Payment","INV-0142 partial ₱200,000 via BDO",<SP s="Partially Paid"/>],["Apr 26","Quotation Sent","QUO-0078 Network Equipment",<SP s="Approved"/>],["Apr 25","Ticket Update","TKT-089 assigned to Juan",<SP s="Open"/>]]}/></div>;

case"portal-orders":return<div><H t="Portal — My Orders"/><T c={["Order","Type","Items","Total","Discount","Payment","Date","Status"]} r={[["ORD-042",<SP s="Online"/>,"2","₱14,348","10% VIP","GCash","Apr 28",<SP s="Processing"/>],["ORD-035",<SP s="Online"/>,"3","₱25,800","10% VIP","Maya","Apr 15",<SP s="Delivered"/>],["ORD-028",<SP s="In Store"/>,"1","₱38,064","10% VIP","Cash","Mar 28",<SP s="Completed"/>],["ORD-019",<SP s="Online"/>,"5","₱30,620","10% VIP","CC Visa","Mar 10",<SP s="Completed"/>]]}/></div>;

case"portal-invoices":return<div><H t="Portal — My Invoices"/><T c={["Invoice","Project","Total","Paid","Credit","Balance","Status","Action"]} r={[["INV-0142","Network Overhaul","₱485K","₱200K","₱45K","₱240K",<SP s="Partially Paid"/>,<B p>Pay Online</B>],["INV-0128","Maintenance","₱35K","₱0","₱0","₱35K",<SP s="Overdue"/>,<B p>Pay Online</B>],["INV-0120","Phase 1 Install","₱320K","₱320K","₱0","₱0",<SP s="Paid"/>,"—"]]}/><I t="Pay online via Xendit: GCash, Maya, Credit Card, Bank Transfer, 7-Eleven."/></div>;

case"portal-proposals":return<div><H t="Portal — Proposals & Quotations"/><T c={["Ref","Type","Title","Total","Rev","Status","Action"]} r={[["PROP-0034","Proposal","Network Overhaul Phase 2","—","3",<SP s="Approved"/>,"—"],["QUO-0078","Quotation","Network Equipment","₱485K","5",<SP s="Approved"/>,"—"],["QUO-0079","Quotation","Phase 3 Extension","₱280K","1",<SP s="Pending"/>,<div style={{display:"flex",gap:4}}><B p>Accept</B><B>Decline</B></div>]]}/></div>;

case"portal-repairs":return<div><H t="Portal — Repairs & Job Orders"/><T c={["Job Order","Device","Issue","Tech","Parts Quote","Status"]} r={[["20260428HKWM3R","MikroTik RB5009","No internet output","Juan","₱8,500 — approved",<SP s="In Repair"/>],["20260415XMWK4P","Dell Latitude","HDD replacement","Paolo","₱12,000",<div style={{display:"flex",gap:4}}><B p>Approve</B><B>Decline</B></div>],["20260320BNRK7L","Cisco 2960X","Port replaced","Juan","₱26,000 — paid",<SP s="Closed"/>]]}/><I t="Approve/decline repair quotation directly from portal. Parts cost uses standard markup."/></div>;

case"portal-projects":return<div><H t="Portal — My Projects"/><T c={["Project","Budget","Progress","Tasks","Milestones","Status"]} r={[["Network Overhaul Phase 2","₱800K","67%","12/18","2/4",<SP s="In Progress"/>],["Network Overhaul Phase 1","₱500K","100%","15/15","3/3",<SP s="Completed"/>]]}/></div>;

case"portal-subs":return<div><H t="Portal — Subscriptions"/><T c={["Plan","Cycle","Amount","Next Billing","Status"]} r={[["Network Maintenance","Monthly","₱15,000","May 3, 2026",<SP s="Active"/>]]}/></div>;

case"portal-payments":return<div><H t="Portal — Payments & Credit"/><div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:18}}><KPI l="Credit Balance" v="₱45,000" a/><KPI l="Total Paid (2026)" v="₱520,000"/><KPI l="Outstanding" v="₱275,000"/></div><T c={["Date","Type","Description","Amount","Method","Ref"]} r={[["Apr 27","Invoice Payment","INV-0142 partial","₱200,000","BDO Transfer","PAY-892"],["Apr 28","E-Com Order","ORD-042 Ubiquiti U6","₱14,348","GCash (Xendit)","xnd_123"],["Apr 15","E-Com Order","ORD-035 Cables","₱25,800","Maya (Xendit)","xnd_118"],["Apr 10","Invoice Payment","INV-0120 full","₱320,000","BDO Transfer","PAY-885"],["Mar 28","POS Purchase","In-store Cisco 2960X","₱38,064","Cash","POS-4489"]]}/></div>;

case"portal-tickets":return<div><H t="Portal — Support Tickets"><B p>+ New Ticket</B></H><T c={["#","Subject","Priority","Created","Status"]} r={[["TKT-089","Internet intermittent — main office",<SP s="Critical"/>,"Apr 28",<SP s="Open"/>],["TKT-075","Request additional AP coverage",<SP s="Medium"/>,"Mar 15",<SP s="Resolved"/>],["TKT-062","Slow network during peak hours",<SP s="High"/>,"Feb 20",<SP s="Closed"/>]]}/></div>;

case"portal-docs":return<div><H t="Portal — Documents"/><T c={["Document","Type","Uploaded","Size","Action"]} r={[["Signed Proposal — Network Overhaul Ph2","Proposal","Apr 20","2.4 MB",<B>Download</B>],["Invoice Receipt — INV-0120","Receipt","Apr 10","1.1 MB",<B>Download</B>],["Warranty Certificate — Cisco 2960X","Warranty","Mar 28","890 KB",<B>Download</B>],["Job Order Report — 20260320BNRK7L","Repair Report","Mar 25","1.5 MB",<B>Download</B>],["Network Assessment Report","Certificate","Feb 15","3.2 MB",<B>Download</B>]]}/></div>;

case"portal-profile":return<div><H t="Portal — Profile"/><div style={{maxWidth:560}}><div style={{display:"flex",alignItems:"center",gap:12,marginBottom:20}}><div style={{width:48,height:48,borderRadius:9999,background:C.warn,display:"flex",alignItems:"center",justifyContent:"center",fontSize:18,fontWeight:700,color:C.abyss}}>VIP</div><div><div style={{fontSize:16,fontWeight:600,color:C.snow}}>Metro Aquatics Inc.</div><div style={{fontSize:12,color:C.slate}}>VIP Customer · Government</div></div></div>{[{l:"Contact Person",v:"Engr. Ramon Cruz"},{l:"Email",v:"ramon@metroaquatics.ph"},{l:"Phone",v:"+63 917 123 4567"},{l:"Address",v:"Lipa City, Batangas"},{l:"Password",v:"••••••••"}].map((f,i)=><div key={i} style={{marginBottom:14}}><label style={{fontSize:12,color:C.slate,display:"block",marginBottom:4}}>{f.l}</label><input defaultValue={f.v} type={f.l==="Password"?"password":"text"} style={{width:"100%",background:C.carbon,border:`1px solid ${C.wb}`,borderRadius:6,padding:"9px 12px",color:C.snow,fontSize:13}}/></div>)}<B p>Save Changes</B></div></div>;

// ═══ SETTINGS ═══
case"settings":return<div><H t="Tenant Settings"/><div style={{maxWidth:560}}>{[{l:"Company",v:"Acme Corp IT Solutions"},{l:"Slug",v:"acme-corp"},{l:"Owner",v:"bonito@acme-corp.ph"},{l:"Plan",v:"Growth"},{l:"Xendit API Key",v:"xnd_production_••••••••"}].map((f,i)=><div key={i} style={{marginBottom:14}}><label style={{fontSize:12,color:C.slate,display:"block",marginBottom:4}}>{f.l}</label><input defaultValue={f.v} style={{width:"100%",background:C.carbon,border:`1px solid ${C.wb}`,borderRadius:6,padding:"9px 12px",color:C.snow,fontSize:13}}/></div>)}<B p>Save</B></div></div>;

case"users":return<div><H t="Users"><B p>+ New</B></H><T c={["Name","Email","Role","Dept","Mobile","Status"]} r={[["Bonito Aguileon","bonito@acme-corp.ph","tenant_super_admin","Mgmt",<SP s="Yes"/>,<SP s="Active"/>],["Maria Santos","maria@acme-corp.ph","project_manager","Ops",<SP s="Yes"/>,<SP s="Active"/>],["Juan dela Cruz","juan@acme-corp.ph","staff","Tech",<SP s="Yes"/>,<SP s="Active"/>],["Rhea Aquino","rhea@acme-corp.ph","inventory_staff","Wh",<SP s="No"/>,<SP s="Active"/>],["Paolo V.","paolo@acme-corp.ph","staff","Tech",<SP s="Yes"/>,<SP s="Active"/>],["Jenny Reyes","jenny@acme-corp.ph","accountant","Finance",<SP s="No"/>,<SP s="Active"/>],["Carlo Tan","carlo@acme-corp.ph","sales_staff","Sales",<SP s="No"/>,<SP s="Active"/>],["Rica Mendoza","rica@acme-corp.ph","hr_manager","HR",<SP s="Yes"/>,<SP s="Active"/>],["Kevin Lim","kevin@acme-corp.ph","support_agent","Support",<SP s="No"/>,<SP s="Active"/>],["Beth Magno","beth@acme-corp.ph","cashier","Store",<SP s="No"/>,<SP s="Active"/>]]}/><I t="13 roles. Single role per user. isEmployee gates mobile + HR record."/></div>;

case"departments":return<div><H t="Departments"><B p>+ New</B></H><T c={["Department","Employees","Head"]} r={[["Management","1","Bonito"],["Operations","1","Maria"],["Technical","2","Juan"],["Warehouse","1","Rhea"],["Finance","1","Jenny"],["Sales","1","Carlo"],["HR","1","Rica"],["Support","1","Kevin"],["Store","1","Beth"]]}/></div>;

case"expense-cats":return<div><H t="Expense Categories"><B p>+ New</B></H><T c={["Name","Slug","Default","Active"]} r={[["Installation Materials","installation_materials",<SP s="Yes"/>,<SP s="Yes"/>],["Transportation","transportation",<SP s="Yes"/>,<SP s="Yes"/>],["Meals","meals",<SP s="Yes"/>,<SP s="Yes"/>],["Accommodation","accommodation",<SP s="Yes"/>,<SP s="Yes"/>],["Equipment Rental","equipment_rental",<SP s="Yes"/>,<SP s="Yes"/>],["Labor","labor",<SP s="Yes"/>,<SP s="Yes"/>],["Permits & Fees","permits_fees",<SP s="Yes"/>,<SP s="Yes"/>],["Communication","communication",<SP s="Yes"/>,<SP s="Yes"/>],["Miscellaneous","miscellaneous",<SP s="Yes"/>,<SP s="Yes"/>],["Gasoline & Fuel","gasoline_fuel",<SP s="No"/>,<SP s="Yes"/>]]}/></div>;

case"smtp":return<div><H t="SMTP Configuration"/><div style={{maxWidth:560}}><div style={{background:"rgba(255,186,0,0.08)",border:"1px solid rgba(255,186,0,0.25)",borderRadius:8,padding:12,marginBottom:18,fontSize:12,color:C.warnP}}>⚠ Configure SMTP to enable email notifications.</div>{[{l:"Host",v:"smtp.gmail.com"},{l:"Port",v:"587"},{l:"User",v:"invoices@acme-corp.ph"},{l:"Password",v:"••••••••"},{l:"From",v:"invoices@acme-corp.ph"},{l:"Name",v:"Acme Corp ERP"}].map((f,i)=><div key={i} style={{marginBottom:14}}><label style={{fontSize:12,color:C.slate,display:"block",marginBottom:4}}>{f.l}</label><input defaultValue={f.v} type={f.l==="Password"?"password":"text"} style={{width:"100%",background:C.carbon,border:`1px solid ${C.wb}`,borderRadius:6,padding:"9px 12px",color:C.snow,fontSize:13}}/></div>)}<div style={{display:"flex",gap:8}}><B p>Save & Enable</B><B>Test</B></div></div></div>;

// ═══ PLATFORM ADMIN ═══
case"pa-tenants":return<div><H t="PA — Tenants"><B p>+ New</B></H><T c={["Slug","Company","Plan","Schema","Status","Created"]} r={[["acme-corp","Acme Corp IT","Growth","t_acme_corp",<SP s="Active"/>,"Jan 2025"],["mabuhay-systems","Mabuhay Systems","Pro","t_mabuhay_systems",<SP s="Active"/>,"Mar 2025"],["batangas-it","Batangas IT Hub","Starter","t_batangas_it_hub",<SP s="Trial"/>,"Apr 2026"],["cebu-tech","Cebu Tech","Growth","t_cebu_tech_partners",<SP s="Active"/>,"Jun 2025"],["davao-netlink","Davao NetLink","Enterprise","t_davao_netlink",<SP s="Active"/>,"Sep 2025"],[<span style={{color:C.sig}}>demo</span>,"Demo","Growth","t_demo",<SP s="Trial"/>,"Seeded"],["manila-net","Manila Networks","Growth","t_manila_networks",<SP s="Suspended"/>,"Nov 2025"]]}/></div>;

case"pa-plans":return<div><H t="PA — Plans"><B p>+ New</B></H><T c={["Plan","Monthly","Annual","Users","Storage","Status"]} r={[["Starter","₱2.5K","₱25K","5","5 GB",<SP s="Active"/>],["Growth","₱5K","₱50K","15","25 GB",<SP s="Active"/>],["Pro","₱10K","₱100K","50","100 GB",<SP s="Active"/>],["Enterprise","₱25K","₱250K","∞","500 GB",<SP s="Active"/>]]}/></div>;

case"pa-billing":return<div><H t="PA — Billing"/><div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:18}}><KPI l="MRR" v="₱67,500" a/><KPI l="Active" v="5"/><KPI l="Overdue" v="1"/><KPI l="Trial" v="2"/></div><T c={["Invoice","Tenant","Amount","Due","Status"]} r={[["TI-042","acme-corp","₱5K","May 1",<SP s="Pending"/>],["TI-041","mabuhay","₱10K","May 1",<SP s="Paid"/>],["TI-040","cebu-tech","₱5K","May 1",<SP s="Pending"/>],["TI-039","davao-net","₱25K","May 1",<SP s="Paid"/>],["TI-038","manila-net","₱5K","Apr 1",<SP s="Past Due"/>]]}/></div>;

case"pa-dlq":return<div><H t="PA — DLQ Monitor"/><T c={["Queue","Failed","Last","Error","Action"]} r={[["tenant-provisioning","0","—","—","—"],["invoice-processing","2","Apr 27","SMTP timeout",<B>Replay</B>],["payroll-processing","0","—","—","—"],["notifications","1","Apr 28","Push expired",<B>Replay</B>],["ecom-order-processing","0","—","—","—"],["xendit-webhook","0","—","—","—"],["job-order-notifications","0","—","—","—"],["demo-reset","0","—","—","—"]]}/><I t="23 queues, DLQ on each. 3x exponential backoff."/></div>;

case"pa-audit":return<div><H t="PA — Audit Log"/><T c={["Time","Tenant","Action","By","Notes"]} r={[["Apr 28","batangas-it","Created","platform_owner","Trial 14d"],["Apr 27","manila-net","Suspended","platform_owner","Overdue 7+ days"],["Apr 25","davao-net","Plan changed","platform_owner","Growth → Enterprise"],["Apr 22","cebu-tech","Billing recorded","platform_owner","TI-037"],["Apr 20","mabuhay","User warning","system","48/50 users"]]}/></div>;

default:return<div style={{padding:48,textAlign:"center",color:C.slate}}>Screen: {sc}</div>;
}};

return(<div style={{display:"flex",flexDirection:"column",height:"100vh",background:C.abyss,color:C.snow,fontFamily:"Inter,system-ui,sans-serif",fontSize:14}}>
<div style={{background:"rgba(255,186,0,0.15)",borderBottom:"1px solid rgba(255,186,0,0.3)",padding:"7px 16px",fontSize:12,color:C.warnP,textAlign:"center",flexShrink:0}}>📐 PHASE 2.8 — Orqafy — 97 screens full fidelity · Not live</div>
<div style={{display:"flex",flex:1,overflow:"hidden"}}>
<div style={{width:sb?230:0,background:C.carbon,borderRight:`1px solid ${C.wb}`,overflow:"auto",flexShrink:0,transition:"width 0.2s"}}>
<div style={{padding:"14px 18px",borderBottom:`1px solid ${C.wb}`,display:"flex",alignItems:"center",gap:8}}>
<div style={{width:26,height:26,borderRadius:6,background:C.sig,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:800,fontSize:12,color:C.abyss,filter:"drop-shadow(0 0 4px #00d992)"}}>O</div>
<div><div style={{fontSize:13,fontWeight:700,color:C.snow}}>Orqafy</div><div style={{fontSize:10,color:C.slate}}>acme-corp</div></div>
</div>
<div style={{padding:"6px 0"}}>{NAV.map((g,gi)=><div key={gi} style={{marginBottom:2}}>
<div style={{padding:"7px 18px 3px",fontSize:10,fontWeight:600,color:C.quat,letterSpacing:0.8}}>{g.l}</div>
{g.items.map(item=><div key={item.id} onClick={()=>setSc(item.id)} style={{padding:"6px 18px",fontSize:12.5,cursor:"pointer",color:sc===item.id?C.snow:C.slate,background:sc===item.id?"rgba(0,217,146,0.08)":"transparent",borderRight:sc===item.id?`2px solid ${C.sig}`:"2px solid transparent",fontWeight:sc===item.id?600:400}} onMouseEnter={e=>{if(sc!==item.id)e.currentTarget.style.background="rgba(255,255,255,0.02)"}} onMouseLeave={e=>{if(sc!==item.id)e.currentTarget.style.background="transparent"}}>{item.n}</div>)}
</div>)}</div>
<div style={{padding:"10px 18px",borderTop:`1px solid ${C.wb}`,fontSize:10,color:C.quat}}>{NAV.reduce((a,g)=>a+g.items.length,0)} screens<div style={{marginTop:3}}>Powered by Powerbyte I.T. Solutions</div></div>
</div>
<div style={{flex:1,overflow:"auto"}}>
<div style={{padding:"8px 22px",borderBottom:`1px solid ${C.wb}`,display:"flex",justifyContent:"space-between",alignItems:"center",background:C.carbon,position:"sticky",top:0,zIndex:10}}>
<div style={{display:"flex",alignItems:"center",gap:10}}><button onClick={()=>setSb(!sb)} style={{background:"none",border:"none",color:C.slate,cursor:"pointer",fontSize:16}}>☰</button><span style={{fontSize:12,color:C.slate}}>acme-corp</span></div>
<div style={{display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:11,color:C.quat}}>Move as one.</span><div style={{width:26,height:26,borderRadius:9999,background:C.sig,display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:700,color:C.abyss}}>B</div></div>
</div>
<div style={{padding:22}}>{R()}</div>
</div>
</div>
<div style={{padding:"5px 16px",borderTop:`1px solid ${C.wb}`,background:C.carbon,fontSize:10,color:C.quat,textAlign:"center",flexShrink:0}}>Orqafy — Move as one. · Powered by Powerbyte I.T. Solutions</div>
</div>);}
